/**
 * Fill the photography gaps on the two Queen Magi island sites with original
 * generated illustration, and only where a real photograph does not exist.
 *
 * Both venues sit on Big Giftun off Hurghada. One of them has a recovered set
 * of its own photographs; the other has almost none. This script never invents
 * a picture of a real place: every scene is a generic Red Sea island day, with
 * no brand, no vessel name, no legible text, no logo and no identifiable
 * person, and the result is never presented as a photograph of the venue. It
 * exists so a site can be reviewed and shown before the professional shoot,
 * and so each generated asset is tracked and replaceable.
 *
 * Real imagery always wins. Generated images are appended after whatever real
 * photographs a record already carries, are never used to replace one, and a
 * gallery is never trimmed. A facility page keeps any hero image it already
 * has. Every write is a compare-and-set against the exact value read, so a
 * retry resumes after the last asset that was persisted and two runs can never
 * double up.
 *
 * Generated frames live in their own `generated/` folder under the site's tour
 * assets. The seeds mirror the real photographs into `tours/<site>/<tour>/`, so
 * the folder is the only reliable way to tell the two apart. Every generated
 * gallery frame also gets an image description that starts "Illustrative
 * image:", the platform's disclosure convention, so the storefront can caption
 * it; a generated page hero gets the same prefix on its description.
 *
 * Images are generated by gpt-image-1.5 through the platform image service.
 *
 * Dry run (no database, image API or upload connection):
 *   npm run images:queen-magi-islands -- --tenant=hula-hula-island
 * Apply in the backend service environment:
 *   npm run images:queen-magi-islands -- --apply --confirm-tenant=hula-hula-island --confirm-assets=generated-only
 */

import { connectDatabase, disconnectDatabase } from '../config/database';
import { Attraction } from '../models/Attraction';
import { Tenant } from '../models/Tenant';
import { generateImageFromPrompt } from '../services/image-generation.service';
import { uploadBase64Image } from '../services/upload.service';
import { imageAltSchema, imageAltTextsSchema, type ImageAltText } from '../utils/imagePresentation';

const IMAGES_PER_TOUR = 6;

/**
 * Applied to every prompt. The first two lines set the look; the rest are the
 * guardrails that keep a generated frame from ever passing as a record of the
 * real venue, a real boat or a real guest.
 */
const STYLE = [
  'Original photorealistic editorial travel photograph of a generic Red Sea island beach day near Hurghada, Egypt.',
  'Premium natural light, believable scale, vivid but realistic turquoise water and pale coral sand, wide landscape composition.',
  'Do not depict or reproduce any real beach club, island venue, resort, company, staff member, guest, uniform, named vessel or identifiable brand.',
  'Do not imitate any existing website, marketplace or social photograph.',
  'People, if present at all, are distant, incidental and not identifiable; no close-up faces.',
  'No text, no legible signage, no logos, no watermark, no collage, no split panels.',
].join(' ');

export interface IslandImagePlanTour {
  slug: string;
  scenes: readonly string[];
}

export interface IslandImagePlanFacility {
  /** Custom page slug on the tenant. */
  slug: string;
  scene: string;
  alt: string;
}

export interface IslandImagePlan {
  tenantSlug: string;
  designMode: 'paradise' | 'hulahula';
  /** Upload folder for generated frames only; never a folder a seed mirrors real photographs into. */
  folder: string;
  /** Path fragment every generated asset URL carries, and no real photograph can. */
  urlMarker: string;
  /** Total site headers to reach, real photographs included. */
  heroTarget: number;
  heroScenes: readonly string[];
  tours: readonly IslandImagePlanTour[];
  facilities: readonly IslandImagePlanFacility[];
}

const PARADISE_PLAN: IslandImagePlan = {
  tenantSlug: 'paradise-island-hurghada',
  designMode: 'paradise',
  folder: 'tours/paradise-island-hurghada/generated',
  urlMarker: '/attractions-network/tours/paradise-island-hurghada/generated/',
  // Four recovered photographs already sit in front of these.
  heroTarget: 7,
  heroScenes: [
    'A wide morning view along a pale sand Red Sea island beach with shallow turquoise water, a reef line darkening offshore and open sky, no buildings or signage in frame.',
    'A generic wooden excursion yacht at anchor off a low sandy island in flat early light, seen from the water with nothing written on the hull.',
    'Warm late afternoon on a Red Sea island shore, long shadows over pale sand and the water turning deep blue towards the reef.',
  ],
  tours: [
    {
      slug: 'paradise-island-cruise-with-lunch-and-snorkelling',
      scenes: [
        'The open upper deck of a generic excursion yacht crossing calm Red Sea water towards a low sandy island, unbranded fittings and nobody recognisable on deck.',
        'A guided snorkelling stop over a healthy Red Sea coral garden in very clear water, photographed from the surface at a respectful distance.',
      ],
    },
    {
      slug: 'paradise-island-dolphin-experience-by-speedboat',
      scenes: [
        'A generic open speedboat running across clear Red Sea water towards a distant low island, spray and wake, no name or marking on the hull.',
        'Wild dolphins moving naturally through open blue water at a respectful distance from a generic unmarked small boat, an observational scene that promises nothing.',
      ],
    },
  ],
  facilities: [],
};

const HULA_HULA_PLAN: IslandImagePlan = {
  tenantSlug: 'hula-hula-island',
  designMode: 'hulahula',
  folder: 'tours/hula-hula-island/generated',
  urlMarker: '/attractions-network/tours/hula-hula-island/generated/',
  // Two client-supplied water frames already sit in front of these.
  heroTarget: 6,
  heroScenes: [
    'A wide dusk view along a Red Sea island beach, the sand warm under a low sun and the water going from amber to deep blue, no buildings or signage in frame.',
    'A generic beach day scene on a pale sand Red Sea island shore in strong midday light, distant incidental figures in the shallows, nothing branded anywhere.',
    'Late golden light across calm shallow turquoise water off a low sandy island, the reef line visible as a dark band offshore.',
    'A generic open speedboat at rest in flat calm water off a Red Sea island in early evening light, unmarked hull, empty horizon behind.',
  ],
  tours: [
    {
      slug: 'hula-hula-island-beach-access',
      scenes: [
        'A quiet stretch of pale sand Red Sea island beach with clear shallow water lapping in, mid morning, unbranded and uncluttered.',
        'Clear shallow turquoise water over rippled pale sand on a Red Sea island shore, photographed straight down from standing height.',
        'A wide island shoreline under strong sun with the reef line offshore and nothing built in frame.',
        'Warm sand and calm water at a Red Sea island beach in late afternoon light, long shadows, no people in the foreground.',
        'A low sandy Red Sea island seen from just offshore, a thin pale beach against deep blue water.',
        'The edge of a shallow turquoise lagoon meeting coral sand on a Red Sea island, small waves, generic and unbranded.',
      ],
    },
    {
      slug: 'hula-hula-island-cruise-with-lunch-and-snorkelling',
      scenes: [
        'The open deck of a generic excursion yacht under way across calm Red Sea water in bright morning light, unbranded fittings and empty sea beyond.',
        'A guided snorkelling stop over a Red Sea coral garden in very clear water, seen from the surface at a respectful distance.',
        'A simple buffet lunch laid out under shade on a Red Sea island in natural light, generic tableware with no labels or branding visible.',
        'Calm turquoise shallows off a pale sand island shore at midday, the reef line dark in the distance.',
        'A generic excursion yacht at anchor off a low sandy island in flat light, unmarked hull, viewed from the water.',
        'A wide view of a Red Sea island beach in the middle of the day, bright sand and water, nothing built or branded in frame.',
      ],
    },
    {
      slug: 'hula-hula-island-sunset-cruise-with-lunch-and-snorkelling',
      scenes: [
        'A generic excursion yacht crossing calm Red Sea water in low late-afternoon light, warm tones, unmarked hull.',
        'The sun low over the Red Sea seen from an open boat deck, amber light on the water, no land or structure in frame.',
        'A snorkelling stop in clear water in the warm light of late afternoon, surface view, respectful distance.',
        'A Red Sea island beach in the last hour of light, warm sand and a deepening blue sea.',
        'The wake of a generic unmarked boat running back towards a distant coastline as the sun goes down over the Red Sea.',
        'A quiet open boat deck at dusk on the Red Sea with generic unbranded fittings, empty horizon and a warm amber sky over dark water.',
      ],
    },
    {
      slug: 'hula-hula-island-semi-submarine',
      scenes: [
        'A generic semi-submarine excursion boat with a low hull sitting deep in calm turquoise Red Sea water, unmarked and unbranded.',
        'A view out through a large generic underwater viewing window at a Red Sea coral reef and tropical fish, clear water, natural light and no notices or markings on the glass.',
        'A Red Sea coral reef seen from just below the surface, fish moving over the coral heads, no divers in frame.',
        'The interior of a generic underwater viewing cabin with windows onto a bright reef, no notices, labels or branding anywhere.',
        'A low unmarked excursion boat moving slowly over shallow reef in very clear water, seen from above the surface.',
        'A wide Red Sea reef scene in bright shallow water, coral and sand, photographed from the surface.',
      ],
    },
    {
      slug: 'hula-hula-island-speedboat-morning-escape',
      scenes: [
        'A generic open speedboat running fast across flat calm Red Sea water in clear morning light, unmarked hull and empty horizon.',
        'The view forward from a generic unmarked open speedboat towards a low sandy island under a bright morning sky.',
        'A speedboat wake cutting across deep blue Red Sea water seen from above the surface, nothing branded in frame.',
        'A low sandy Red Sea island approached from the water in the middle of the morning, pale beach against turquoise shallows.',
        'A generic unmarked speedboat at rest in shallow turquoise water off an island beach in bright light.',
        'Bright morning light on a pale sand island shore with calm clear water and an empty horizon.',
      ],
    },
    {
      slug: 'hula-hula-island-speedboat-sunset',
      scenes: [
        'A generic open speedboat running across the Red Sea in low warm afternoon light, unmarked hull, long shadows on the water.',
        'A low sandy island beach in the warm light of late afternoon, the sea going from turquoise to deep blue.',
        'The sun low over the Red Sea seen across open water from a small boat, amber light and no land in frame.',
        'The wake of a generic unmarked speedboat in warm evening light on calm Red Sea water, seen from above the surface.',
        'A pale sand island shore at dusk with the last warm light on the water and an empty horizon.',
        'A generic unmarked speedboat moored in shallow water at the end of the day, warm sky behind.',
      ],
    },
    {
      slug: 'hula-hula-island-dolphin-experience-by-speedboat',
      scenes: [
        'Wild dolphins moving naturally through open blue Red Sea water at a respectful distance, an observational scene that promises nothing.',
        'A generic open speedboat holding station in deep blue open water while dolphins pass well clear of it, unmarked hull.',
        'Open Red Sea water under bright sun with a dorsal fin breaking the surface some way off, a distant natural sighting.',
        'A speedboat running across deep offshore water away from land, spray and blue, nothing branded in frame.',
        'A pale sand Red Sea island beach seen from the water after an offshore run, clear shallows in front.',
        'Deep blue open Red Sea water and an empty horizon photographed from a generic unmarked small boat at speed.',
      ],
    },
    {
      slug: 'hula-hula-island-private-speedboat-morning',
      scenes: [
        'A single generic unmarked speedboat alone on flat calm Red Sea water in clear morning light, no other vessel in frame.',
        'An empty open speedboat deck with clean unbranded fittings, photographed in bright natural light with the sea beyond.',
        'A private speedboat at anchor in shallow turquoise water off an empty pale sand island beach, no one else around.',
        'A low sandy Red Sea island approached by a single generic unmarked small boat in the morning, calm water and open sky.',
        'A quiet island shoreline with one unmarked boat moored offshore, bright midday light, nothing built in frame.',
        'Flat calm Red Sea water and an empty horizon seen from an unmarked open boat in the morning.',
      ],
    },
    {
      slug: 'hula-hula-island-private-speedboat-sunset',
      scenes: [
        'A single generic unmarked speedboat alone on calm Red Sea water in low warm evening light, no other vessel in frame.',
        'An empty open speedboat deck in warm late light with the sea and an empty horizon beyond, unbranded fittings.',
        'A single generic unmarked speedboat moored off an empty island beach as the sun goes down, warm sky over deep blue water.',
        'A pale sand island shore in the last light of the day with one unmarked boat offshore.',
        'Warm evening light across calm Red Sea water seen from a small boat, no land in frame.',
        'A quiet dusk scene on the Red Sea with a single unmarked hull silhouetted against an amber sky.',
      ],
    },
  ],
  facilities: [
    {
      slug: 'beach-access',
      scene: 'A wide stretch of pale coral sand on a Red Sea island with clear shallow turquoise water and a dark reef line offshore, bright natural light, nothing built or branded in frame.',
      alt: 'A generic Red Sea island beach with pale sand and clear shallow water',
    },
    {
      slug: 'hula-hula-water-sports',
      scene: 'A generic inflatable towable ride being pulled across flat turquoise water off a Red Sea island beach, distant incidental figures, unmarked equipment and boat.',
      alt: 'A generic towable water sports ride on calm turquoise water off an island beach',
    },
    {
      slug: 'hula-hula-massage',
      scene: 'A simple unbranded massage bed set up in shade on the open deck of a generic excursion boat, calm Red Sea water beyond, no people in frame.',
      alt: 'A simple massage bed in the shade on an open boat deck above calm water',
    },
    {
      slug: 'island-lunch',
      scene: 'A simple buffet lunch laid out under shade on a Red Sea island in natural light, generic tableware and no labels, packaging or branding visible anywhere.',
      alt: 'A simple buffet lunch laid out under shade on an island',
    },
  ],
};

export const QUEEN_MAGI_ISLAND_IMAGE_PLANS: readonly IslandImagePlan[] = [PARADISE_PLAN, HULA_HULA_PLAN];

export function validateIslandImagePlan(): string[] {
  const errors: string[] = [];
  if (QUEEN_MAGI_ISLAND_IMAGE_PLANS.length !== 2) errors.push('The plan must target both island sites.');
  if (!/no text/i.test(STYLE) || !/no logos/i.test(STYLE) || !/do not imitate/i.test(STYLE)
    || !/do not depict or reproduce/i.test(STYLE) || !/not identifiable/i.test(STYLE)) {
    errors.push('The generated-only, no-brand and no-person prompt guard is missing.');
  }

  const tenantSlugs = new Set<string>();
  for (const plan of QUEEN_MAGI_ISLAND_IMAGE_PLANS) {
    if (tenantSlugs.has(plan.tenantSlug)) errors.push(`Duplicate plan: ${plan.tenantSlug}`);
    tenantSlugs.add(plan.tenantSlug);
    if (!plan.urlMarker.includes(plan.tenantSlug)) errors.push(`The asset path must be scoped to the site: ${plan.tenantSlug}`);
    if (plan.folder !== `tours/${plan.tenantSlug}/generated` || plan.urlMarker !== `/attractions-network/${plan.folder}/`) {
      errors.push(`Generated frames must live in their own folder, apart from the real photographs: ${plan.tenantSlug}`);
    }
    if (plan.heroScenes.length < 3 || plan.heroScenes.length > 4) errors.push(`Between three and four site header scenes are required: ${plan.tenantSlug}`);
    if (plan.heroTarget < plan.heroScenes.length) errors.push(`Header target is below the number of scenes: ${plan.tenantSlug}`);
    for (const scene of plan.heroScenes) {
      if (scene.trim().length < 80) errors.push(`Header scene is too thin: ${plan.tenantSlug}`);
      if (sceneNeedsQualifier(scene)) errors.push(`Header scene depicts something brandable without a generic qualifier: ${plan.tenantSlug}`);
      if (NAMES_A_REAL_PLACE.test(scene)) errors.push(`Header scene names a real venue or operator: ${plan.tenantSlug}`);
    }

    const tourSlugs = new Set<string>();
    for (const tour of plan.tours) {
      if (tourSlugs.has(tour.slug)) errors.push(`Duplicate image target: ${tour.slug}`);
      tourSlugs.add(tour.slug);
      // Real photographs are mirrored into tours/<site>/<tour>/, so a tour named after the folder would blur the line.
      if (tour.slug === 'generated') errors.push(`A tour slug may not share the generated folder name: ${plan.tenantSlug}`);
      if (!tour.scenes.length || tour.scenes.length > IMAGES_PER_TOUR) errors.push(`Between one and ${IMAGES_PER_TOUR} scenes are required: ${tour.slug}`);
      for (const scene of tour.scenes) {
        if (scene.trim().length < 80) errors.push(`Scene is too thin: ${tour.slug}`);
        if (sceneNeedsQualifier(scene)) errors.push(`Scene depicts something brandable without a generic qualifier: ${tour.slug}`);
        if (NAMES_A_REAL_PLACE.test(scene)) errors.push(`Scene names a real venue or operator: ${tour.slug}`);
        if (!imageAltSchema.safeParse(illustrativeAlt(scene)).success) errors.push(`Scene cannot be described as an illustration: ${tour.slug}`);
      }
      // A site's tours may never be filled from the other site's plan.
      const otherPrefix = plan.tenantSlug === 'hula-hula-island' ? 'paradise-' : 'hula-hula-';
      if (tour.slug.startsWith(otherPrefix)) errors.push(`Target belongs to the other site: ${tour.slug}`);
    }

    const pageSlugs = new Set<string>();
    for (const facility of plan.facilities) {
      if (pageSlugs.has(facility.slug)) errors.push(`Duplicate page target: ${facility.slug}`);
      pageSlugs.add(facility.slug);
      if (facility.scene.trim().length < 80) errors.push(`Page scene is too thin: ${facility.slug}`);
      if (sceneNeedsQualifier(facility.scene)) errors.push(`Page scene depicts something brandable without a generic qualifier: ${facility.slug}`);
      if (NAMES_A_REAL_PLACE.test(facility.scene)) errors.push(`Page scene names a real venue or operator: ${facility.slug}`);
      if (!facility.alt.trim()) errors.push(`Page image needs a description: ${facility.slug}`);
      if (!imageAltSchema.safeParse(illustrativeAlt(facility.alt)).success) errors.push(`Page image description is invalid: ${facility.slug}`);
    }
  }
  return errors;
}

/**
 * A scene that puts a boat, a deck, equipment, a meal or people in frame is a
 * scene that could acquire a brand, a vessel name or a recognisable face. Those
 * must carry their own qualifier rather than relying on the shared style block.
 * An empty landscape has nothing to brand and needs none.
 */
const DEPICTS_SOMETHING_BRANDABLE = /\b(boat|yacht|speedboat|vessel|hull|deck|cabin|equipment|buffet|lunch|massage|people|figures|guest|crew|ride|window)/i;
const CARRIES_QUALIFIER = /\b(generic|unbranded|unmarked|incidental|no |nothing |without )/i;

/** Neither venue, the operator, nor any real named place may be asked for. */
const NAMES_A_REAL_PLACE = /\bhula|paradise island|paradise beach|queen magi|orange bay\b/i;

export function sceneNeedsQualifier(scene: string): boolean {
  return DEPICTS_SOMETHING_BRANDABLE.test(scene) && !CARRIES_QUALIFIER.test(scene);
}

/** The platform's disclosure convention: the storefront captions any image whose description starts with this. */
export const ILLUSTRATIVE_IMAGE_PREFIX = 'Illustrative image:';

/** A frame this script generated, told apart from a real photograph by its folder alone. */
export function isGeneratedAsset(url: string, plan: Pick<IslandImagePlan, 'urlMarker'>): boolean {
  return url.includes(plan.urlMarker);
}

/**
 * The description stored with a generated frame. It names what the frame shows,
 * in the scene's own opening words, and always declares itself illustrative.
 */
export function illustrativeAlt(description: string): string {
  const opening = description.split(/[,.;]/)[0]!.trim();
  return `${ILLUSTRATIVE_IMAGE_PREFIX} ${opening.charAt(0).toLowerCase()}${opening.slice(1)}.`;
}

const fullPrompt = (scene: string): string => `${scene} ${STYLE}`;

function argValue(name: string): string | null {
  const prefix = `--${name}=`;
  const hit = process.argv.slice(2).find((arg) => arg.startsWith(prefix));
  return hit ? hit.slice(prefix.length) : null;
}

function selectPlan(slug: string | null): IslandImagePlan {
  const plan = QUEEN_MAGI_ISLAND_IMAGE_PLANS.find((candidate) => candidate.tenantSlug === slug);
  if (!plan) {
    throw new Error(`Name the site to work on: --tenant=${QUEEN_MAGI_ISLAND_IMAGE_PLANS.map((item) => item.tenantSlug).join(' or --tenant=')}`);
  }
  return plan;
}

async function generateAndUpload(scene: string, folder: string, publicId: string, urlMarker: string): Promise<string> {
  const { base64, mimeType } = await generateImageFromPrompt({
    prompt: fullPrompt(scene),
    size: '1536x1024',
    quality: 'high',
    outputFormat: 'jpeg',
  });
  const uploaded = await uploadBase64Image(`data:${mimeType};base64,${base64}`, folder, { publicId, overwrite: true });
  if (!uploaded.url.includes(urlMarker)) throw new Error(`Upload returned an unexpected asset path for ${publicId}.`);
  return uploaded.url;
}

async function applyImagePlan(plan: IslandImagePlan): Promise<void> {
  const args = new Set(process.argv.slice(2));
  if (!args.has(`--confirm-tenant=${plan.tenantSlug}`) || !args.has('--confirm-assets=generated-only')) {
    throw new Error(`Apply fence missing. Pass --confirm-tenant=${plan.tenantSlug} and --confirm-assets=generated-only.`);
  }

  await connectDatabase();
  try {
    const tenant = await Tenant.findOne({ slug: plan.tenantSlug }).select('_id slug status designMode heroImages customPages');
    if (!tenant || tenant.status !== 'active') throw new Error(`The active ${plan.tenantSlug} site was not found.`);
    if (tenant.designMode !== plan.designMode) {
      throw new Error(`Refusing to work on a site in the wrong design: ${tenant.designMode}.`);
    }

    const targetSlugs = plan.tours.map((item) => item.slug);
    const tours = targetSlugs.length
      ? await Attraction.find({ slug: { $in: targetSlugs }, ownerTenantId: tenant._id })
        .select('_id slug status ownerTenantId tenantIds images imageAltTexts presentationRevision')
      : [];
    if (tours.length !== targetSlugs.length) {
      const found = new Set(tours.map((tour) => tour.slug));
      throw new Error(`Missing catalogue records on this site: ${targetSlugs.filter((slug) => !found.has(slug)).join(', ')}`);
    }
    for (const tour of tours) {
      const owned = String(tour.ownerTenantId) === String(tenant._id)
        && tour.tenantIds.some((tenantId) => String(tenantId) === String(tenant._id));
      if (!owned || tour.status !== 'active') throw new Error(`Refusing an image write outside this site's catalogue: ${tour.slug}.`);
      if ((tour.images || []).length > IMAGES_PER_TOUR) throw new Error(`Refusing to trim an expanded gallery on ${tour.slug}.`);
    }

    console.log(JSON.stringify({
      mode: 'pre-apply-report',
      tenant: plan.tenantSlug,
      generatedOnly: true,
      heroes: { present: (tenant.heroImages || []).length, target: plan.heroTarget },
      tours: tours.map((tour) => ({
        slug: tour.slug,
        present: tour.images.length,
        real: tour.images.filter((url) => !isGeneratedAsset(url, plan)).length,
        remaining: Math.max(0, IMAGES_PER_TOUR - tour.images.length),
      })),
      pages: plan.facilities.map((facility) => ({
        slug: facility.slug,
        hasImage: Boolean((tenant.customPages || []).find((page) => page.slug === facility.slug)?.heroImage),
      })),
    }, null, 2));

    // Tour galleries: generated frames are appended after the real photographs.
    for (const item of plan.tours) {
      const tour = tours.find((candidate) => candidate.slug === item.slug)!;
      let currentImages = [...(tour.images || [])];
      let currentAlts: ImageAltText[] = (tour.imageAltTexts || []).map((row) => ({ url: row.url, alt: row.alt }));
      let revision = tour.presentationRevision ?? 0;
      // Real photographs keep their places; the scene list is indexed from the
      // first generated frame, so a retry resumes exactly where it stopped.
      const realCount = currentImages.filter((url) => !isGeneratedAsset(url, plan)).length;
      for (let index = currentImages.length; index < IMAGES_PER_TOUR; index += 1) {
        const sceneIndex = index - realCount;
        if (sceneIndex >= item.scenes.length) {
          console.log(JSON.stringify({ slug: item.slug, stopped: 'the plan has no further scene for this gallery', filled: currentImages.length }));
          break;
        }
        const scene = item.scenes[sceneIndex]!;
        const url = await generateAndUpload(scene, plan.folder, `${item.slug}-generated-${String(sceneIndex + 1).padStart(2, '0')}`, plan.urlMarker);
        const nextImages = [...currentImages, url];
        const nextAlts = imageAltTextsSchema.parse([
          ...currentAlts.filter((row) => row.url !== url),
          { url, alt: illustrativeAlt(scene) },
        ]);
        // Same fence as the admin editor: the gallery read and its presentation
        // revision must both still hold, and the revision moves on with the write.
        const result = await Attraction.updateOne(
          {
            _id: tour._id,
            ownerTenantId: tenant._id,
            images: currentImages,
            ...(revision === 0
              ? { $or: [{ presentationRevision: 0 }, { presentationRevision: { $exists: false } }] }
              : { presentationRevision: revision }),
          },
          { $set: { images: nextImages, imageAltTexts: nextAlts }, $inc: { presentationRevision: 1 } },
        );
        if (result.modifiedCount !== 1) throw new Error(`Concurrent image edit detected on ${item.slug}; the asset was not attached.`);
        currentImages = nextImages;
        currentAlts = nextAlts;
        revision += 1;
        console.log(JSON.stringify({ slug: item.slug, image: index + 1, url }));
      }
    }

    // Facility pages: only a page with no photograph of its own is filled.
    for (const facility of plan.facilities) {
      const page = (tenant.customPages || []).find((candidate) => candidate.slug === facility.slug);
      if (!page) throw new Error(`Missing page on this site: ${facility.slug}.`);
      if (page.heroImage) {
        console.log(JSON.stringify({ page: facility.slug, skipped: 'already has an image' }));
        continue;
      }
      const url = await generateAndUpload(facility.scene, plan.folder, `page-${facility.slug}`, plan.urlMarker);
      const result = await Tenant.updateOne(
        { _id: tenant._id, slug: plan.tenantSlug, customPages: { $elemMatch: { slug: facility.slug, heroImage: { $in: [null, ''] } } } },
        { $set: { 'customPages.$.heroImage': url, 'customPages.$.heroImageAlt': imageAltSchema.parse(illustrativeAlt(facility.alt)) } },
      );
      if (result.modifiedCount !== 1) throw new Error(`Concurrent page edit detected on ${facility.slug}; the asset was not attached.`);
      console.log(JSON.stringify({ page: facility.slug, url }));
    }

    // Site headers: generated frames are appended after the real photographs.
    let heroImages = [...(tenant.heroImages || [])];
    if (heroImages.length > plan.heroTarget) throw new Error('Refusing to trim an expanded site header set.');
    const realHeroCount = heroImages.filter((url) => !isGeneratedAsset(url, plan)).length;
    for (let index = heroImages.length; index < plan.heroTarget; index += 1) {
      const sceneIndex = index - realHeroCount;
      if (sceneIndex >= plan.heroScenes.length) {
        console.log(JSON.stringify({ stopped: 'the plan has no further site header scene', filled: heroImages.length }));
        break;
      }
      const scene = plan.heroScenes[sceneIndex];
      const url = await generateAndUpload(scene, plan.folder, `hero-generated-${String(sceneIndex + 1).padStart(2, '0')}`, plan.urlMarker);
      const next = [...heroImages, url];
      const result = await Tenant.updateOne(
        { _id: tenant._id, slug: plan.tenantSlug, heroImages },
        { $set: { heroImages: next } },
      );
      if (result.modifiedCount !== 1) throw new Error('Concurrent site header edit detected; the asset was not attached.');
      heroImages = next;
      console.log(JSON.stringify({ hero: index + 1, url }));
    }

    const refreshed = await Attraction.find({ slug: { $in: targetSlugs }, ownerTenantId: tenant._id }).select('slug images');
    // A gallery is complete when it holds every frame the plan can supply, which
    // is the target unless the plan simply has fewer scenes than the gap.
    const short = refreshed.filter((tour) => {
      const item = plan.tours.find((candidate) => candidate.slug === tour.slug)!;
      const real = tour.images.filter((url) => !isGeneratedAsset(url, plan)).length;
      return tour.images.length < Math.min(IMAGES_PER_TOUR, real + item.scenes.length);
    });
    if (short.length) throw new Error(`Post-apply image check failed: ${short.map((tour) => tour.slug).join(', ')}`);

    console.log(JSON.stringify({
      mode: 'applied',
      tenant: plan.tenantSlug,
      generatedOnly: true,
      tours: refreshed.length,
      images: refreshed.reduce((sum, tour) => sum + tour.images.length, 0),
      generated: refreshed.reduce((sum, tour) => sum + tour.images.filter((url) => isGeneratedAsset(url, plan)).length, 0),
      siteHeaders: heroImages.length,
      safeguards: [
        'no real photograph replaced and no gallery trimmed',
        'every frame generic, unbranded and never presented as the venue',
        'every write a compare-and-set against the value read',
      ],
    }, null, 2));
  } finally {
    await disconnectDatabase();
  }
}

export async function main(): Promise<void> {
  const errors = validateIslandImagePlan();
  if (errors.length) throw new Error(`Image plan is invalid:\n- ${errors.join('\n- ')}`);

  const plan = selectPlan(argValue('tenant') || argValue('confirm-tenant'));
  if (!new Set(process.argv.slice(2)).has('--apply')) {
    console.log(JSON.stringify({
      mode: 'dry-run',
      tenant: plan.tenantSlug,
      designMode: plan.designMode,
      generatedOnly: true,
      folder: `attractions-network/${plan.folder}`,
      siteHeaders: { target: plan.heroTarget, scenes: plan.heroScenes.length },
      galleryTarget: IMAGES_PER_TOUR,
      tours: plan.tours.map((item) => ({ slug: item.slug, scenes: item.scenes.length })),
      pages: plan.facilities.map((item) => item.slug),
      safeguards: [
        'no database connection',
        'no image generation',
        'no upload',
        'no real photograph replaced',
        'no source, marketplace or competitor imagery',
      ],
    }, null, 2));
    return;
  }
  await applyImagePlan(plan);
}

if (require.main === module) {
  main().catch((error) => {
    console.error(`[queen-magi-island-images] ${error instanceof Error ? error.message : String(error)}`);
    process.exitCode = 1;
  });
}
