/**
 * Create an original four-image set for each Cave Divers catalogue record.
 *
 * Every image is generated by gpt-image-1.5, uploaded to the Cave Divers
 * Cloudinary folder, then persisted with an exact tenant-and-current-images
 * compare-and-set. The script is resumable: a retry starts after the last
 * successfully persisted image and never imports a source or competitor asset.
 *
 * Dry run (no database, image API, or Cloudinary connection):
 *   npm run images:cave-divers
 * Apply in the backend service environment:
 *   npm run images:cave-divers -- --apply --confirm-tenant=cave-divers --confirm-assets=generated-only
 */

import { connectDatabase, disconnectDatabase } from '../config/database';
import { Attraction } from '../models/Attraction';
import { Tenant } from '../models/Tenant';
import { generateImageFromPrompt } from '../services/image-generation.service';
import { uploadBase64Image } from '../services/upload.service';

const TENANT_SLUG = 'cave-divers';
const IMAGE_FOLDER = 'tours/cave-divers';
const IMAGE_URL_MARKER = '/attractions-network/tours/cave-divers/';
const IMAGES_PER_TOUR = 4;

const STYLE = [
  'Original photorealistic editorial travel photograph of a generic Red Sea experience in Hurghada, Egypt.',
  'Premium natural-light photography, believable people and equipment, vivid but realistic underwater colour, wide landscape composition.',
  'Do not depict or reproduce a real dive centre, employee, instructor, customer, logo, named vessel, uniform, or identifiable brand.',
  'Do not imitate any source-site or marketplace photograph.',
  'No text, no legible signage, no logos, no watermark, no collage, no split panels.',
].join(' ');

export interface CaveDiversImagePlanItem {
  slug: string;
  scenes: readonly [string, string, string, string];
}

export const CAVE_DIVERS_IMAGE_PLAN: readonly CaveDiversImagePlanItem[] = [
  {
    slug: 'cave-divers-red-sea-daily-diving',
    scenes: [
      'A small Red Sea day boat leaving a Hurghada marina in clear early-morning light, dive cylinders secured on deck and a mixed adult group preparing calmly.',
      'Two certified scuba divers moving beside a healthy Red Sea coral garden in clear blue water, observed from a respectful wide angle.',
      'A divemaster giving a concise pre-dive briefing on a tidy boat deck, guests checking masks and fins, faces generic and unbranded.',
      'A relaxed surface interval on a Red Sea boat with a simple lunch table, hot drinks and the reef horizon beyond, no product labels visible.',
    ],
  },
  {
    slug: 'cave-divers-multi-day-daily-diving',
    scenes: [
      'Experienced divers reviewing a multi-day reef plan around a clean map table on a Red Sea boat, with no readable map labels or writing.',
      'A calm morning equipment check with several assembled scuba sets lined neatly along an unbranded Hurghada dive boat.',
      'A pair of divers exploring a different Red Sea reef wall with schooling fish, showing the variety of a multi-day programme.',
      'Divers rinsing and organising equipment after a day at sea while another guest records memories in a closed, unreadable logbook.',
    ],
  },
  {
    slug: 'cave-divers-discover-scuba-diving',
    scenes: [
      'A patient instructor explaining a regulator and mask to two first-time adult divers beside shallow turquoise water, generic unbranded equipment.',
      'A beginner practising calm breathing and mask skills with an instructor in bright, waist-deep sheltered Red Sea water.',
      'A closely supervised first scuba dive over a gentle sandy-bottom reef with small colourful fish and plenty of open water.',
      'A smiling beginner and instructor returning to a generic day boat after a shallow introductory dive, natural candid atmosphere.',
    ],
  },
  {
    slug: 'cave-divers-open-water-diver-course',
    scenes: [
      'An instructor and two adult students learning how scuba equipment fits together at an uncluttered open-air training station near the Red Sea.',
      'Two students practising buoyancy with an instructor over a shallow sandy training area, safe spacing and clear hand signals.',
      'A student pair completing a supervised open-water skills dive along a gentle coral slope in excellent visibility.',
      'New divers celebrating course progress on a boat deck with masks in hand and the Hurghada coastline behind, no certificates or readable text.',
    ],
  },
  {
    slug: 'cave-divers-dolphin-house-sea-trip',
    scenes: [
      'A Red Sea day boat travelling toward an offshore reef in soft morning light, snorkelling gear arranged for a full day on the water.',
      'Wild dolphins passing naturally at a respectful distance from snorkellers in open blue water, observational encounter with no touching or chasing.',
      'Snorkellers exploring a bright reef edge with a guide, broad natural scene that does not promise any wildlife encounter.',
      'Guests sharing lunch and drinks during a relaxed surface interval on an unbranded boat with open sea all around.',
    ],
  },
  {
    slug: 'cave-divers-orange-bay-giftun-island',
    scenes: [
      'A classic Red Sea island beach with pale sand, clear turquoise shallows and a small unbranded excursion boat anchored offshore.',
      'Guests stepping carefully from a tender into shallow water for an island landing, relaxed family-friendly atmosphere and generic faces.',
      'A guided snorkelling stop above a colourful Red Sea coral garden before the island visit, photographed from water level.',
      'A simple lunch and soft-drink service on a sunlit boat deck after snorkelling, Orange Bay style scenery in the distance without signs or logos.',
    ],
  },
  {
    slug: 'cave-divers-glass-boat-half-day',
    scenes: [
      'A compact generic glass-bottom excursion boat crossing calm turquoise Red Sea water near Hurghada in bright morning light.',
      'Families looking through large glass viewing panels at coral and tropical fish below, no readable notices or vessel branding.',
      'A half-day snorkelling stop beside a shallow reef, with some guests remaining comfortably on the viewing boat.',
      'A brief island landing with guests walking through clear shallows toward pale sand while the small glass-bottom boat waits offshore.',
    ],
  },
] as const;

export function validateCaveDiversImagePlan(): string[] {
  const errors: string[] = [];
  if (CAVE_DIVERS_IMAGE_PLAN.length !== 7) errors.push('The image plan must target exactly seven catalogue records.');
  const slugs = new Set<string>();
  for (const item of CAVE_DIVERS_IMAGE_PLAN) {
    if (slugs.has(item.slug)) errors.push(`Duplicate image target: ${item.slug}`);
    slugs.add(item.slug);
    if (item.scenes.length !== IMAGES_PER_TOUR) errors.push(`Expected four scenes for ${item.slug}.`);
    for (const scene of item.scenes) {
      if (scene.trim().length < 80) errors.push(`Scene is too thin for ${item.slug}.`);
    }
  }
  if (!/no text/i.test(STYLE) || !/no logos/i.test(STYLE) || !/do not imitate/i.test(STYLE)) {
    errors.push('The generated-only and no-brand prompt guard is missing.');
  }
  return errors;
}

const fullPrompt = (scene: string): string => `${scene} ${STYLE}`;

async function applyImagePlan(): Promise<void> {
  const args = new Set(process.argv.slice(2));
  if (!args.has(`--confirm-tenant=${TENANT_SLUG}`) || !args.has('--confirm-assets=generated-only')) {
    throw new Error(
      `Apply fence missing. Pass --confirm-tenant=${TENANT_SLUG} and --confirm-assets=generated-only.`,
    );
  }

  await connectDatabase();
  try {
    const tenant = await Tenant.findOne({ slug: TENANT_SLUG }).select('_id slug status heroImages');
    if (!tenant || tenant.status !== 'active') throw new Error('The active Cave Divers tenant was not found.');

    const targetSlugs = CAVE_DIVERS_IMAGE_PLAN.map((item) => item.slug);
    const tours = await Attraction.find({ slug: { $in: targetSlugs } })
      .select('_id slug status enquiryOnly ownerTenantId tenantIds images');
    if (tours.length !== targetSlugs.length) {
      const found = new Set(tours.map((tour) => tour.slug));
      throw new Error(`Missing catalogue records: ${targetSlugs.filter((slug) => !found.has(slug)).join(', ')}`);
    }

    for (const tour of tours) {
      const owned = String(tour.ownerTenantId) === String(tenant._id)
        && tour.tenantIds.some((tenantId) => String(tenantId) === String(tenant._id));
      if (!owned || tour.status !== 'active' || tour.enquiryOnly !== true) {
        throw new Error(`Refusing image write outside the Cave Divers enquiry-only catalogue: ${tour.slug}.`);
      }
      if ((tour.images || []).some((url) => !url.includes(IMAGE_URL_MARKER))) {
        throw new Error(`Refusing to replace non-Cave imagery already present on ${tour.slug}.`);
      }
      if ((tour.images || []).length > IMAGES_PER_TOUR) {
        throw new Error(`Refusing to trim an expanded gallery on ${tour.slug}.`);
      }
    }

    console.log(JSON.stringify({
      mode: 'pre-apply-report',
      tenant: TENANT_SLUG,
      targets: CAVE_DIVERS_IMAGE_PLAN.map((item) => {
        const tour = tours.find((candidate) => candidate.slug === item.slug)!;
        return { slug: item.slug, existing: tour.images.length, remaining: IMAGES_PER_TOUR - tour.images.length };
      }),
    }, null, 2));

    for (const item of CAVE_DIVERS_IMAGE_PLAN) {
      const tour = tours.find((candidate) => candidate.slug === item.slug)!;
      let currentImages = [...(tour.images || [])];
      for (let index = currentImages.length; index < IMAGES_PER_TOUR; index += 1) {
        const { base64, mimeType } = await generateImageFromPrompt({
          prompt: fullPrompt(item.scenes[index]),
          size: '1536x1024',
          quality: 'high',
          outputFormat: 'jpeg',
        });
        const uploaded = await uploadBase64Image(
          `data:${mimeType};base64,${base64}`,
          IMAGE_FOLDER,
          { publicId: `${item.slug}-${String(index + 1).padStart(2, '0')}`, overwrite: true },
        );
        if (!uploaded.url.includes(IMAGE_URL_MARKER)) {
          throw new Error(`Upload returned an unexpected asset path for ${item.slug}.`);
        }
        const nextImages = [...currentImages, uploaded.url];
        const result = await Attraction.updateOne(
          {
            _id: tour._id,
            ownerTenantId: tenant._id,
            enquiryOnly: true,
            images: currentImages,
          },
          { $set: { images: nextImages } },
        );
        if (result.modifiedCount !== 1) {
          throw new Error(`Concurrent image edit detected on ${item.slug}; uploaded asset was not attached.`);
        }
        currentImages = nextImages;
        console.log(JSON.stringify({ slug: item.slug, image: index + 1, url: uploaded.url }));
      }
    }

    const refreshed = await Attraction.find({ slug: { $in: targetSlugs }, ownerTenantId: tenant._id })
      .select('slug images');
    const heroSlugs = [
      'cave-divers-red-sea-daily-diving',
      'cave-divers-discover-scuba-diving',
      'cave-divers-dolphin-house-sea-trip',
      'cave-divers-orange-bay-giftun-island',
    ];
    const heroImages = heroSlugs.map((slug) => {
      const image = refreshed.find((tour) => tour.slug === slug)?.images?.[0];
      if (!image) throw new Error(`Hero source image is missing for ${slug}.`);
      return image;
    });
    const currentHeroImages = [...(tenant.heroImages || [])];
    if (currentHeroImages.some((url) => !url.includes(IMAGE_URL_MARKER))) {
      throw new Error('Refusing to replace tenant hero imagery not created by this pipeline.');
    }
    if (JSON.stringify(currentHeroImages) !== JSON.stringify(heroImages)) {
      const result = await Tenant.updateOne(
        { _id: tenant._id, slug: TENANT_SLUG, heroImages: currentHeroImages },
        { $set: { heroImages } },
      );
      if (result.modifiedCount !== 1) throw new Error('Concurrent tenant hero edit detected; no hero array was replaced.');
    }

    const invalid = refreshed.filter((tour) => (
      tour.images.length !== IMAGES_PER_TOUR
      || tour.images.some((url) => !url.includes(IMAGE_URL_MARKER))
    ));
    if (invalid.length) throw new Error(`Post-apply image verification failed: ${invalid.map((tour) => tour.slug).join(', ')}`);
    console.log(JSON.stringify({
      mode: 'applied',
      generatedOnly: true,
      tours: refreshed.length,
      images: refreshed.reduce((sum, tour) => sum + tour.images.length, 0),
      tenantHeroes: heroImages.length,
    }, null, 2));
  } finally {
    await disconnectDatabase();
  }
}

export async function main(): Promise<void> {
  const errors = validateCaveDiversImagePlan();
  if (errors.length) throw new Error(`Image plan is invalid:\n- ${errors.join('\n- ')}`);
  if (!new Set(process.argv.slice(2)).has('--apply')) {
    console.log(JSON.stringify({
      mode: 'dry-run',
      tenant: TENANT_SLUG,
      generatedOnly: true,
      folder: `attractions-network/${IMAGE_FOLDER}`,
      targets: CAVE_DIVERS_IMAGE_PLAN.map((item) => ({ slug: item.slug, images: item.scenes.length })),
      safeguards: ['no database connection', 'no image generation', 'no upload', 'no source or competitor imagery'],
    }, null, 2));
    return;
  }
  await applyImagePlan();
}

if (require.main === module) {
  main().catch((error) => {
    console.error(`[cave-divers-images] ${error instanceof Error ? error.message : String(error)}`);
    process.exitCode = 1;
  });
}
