import express from 'express';
import request from 'supertest';
import mongoose, { Types } from 'mongoose';
import { spawnSync } from 'child_process';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import { planLocalization,executeLocalizationPlan,localizationDigest } from '../services/localizationMigration.service';
import { sign } from 'jsonwebtoken';
import { Attraction } from '../models/Attraction';
import { Destination } from '../models/Destination';
import { DestinationTranslation } from '../models/DestinationTranslation';
import destinationRoutes from '../routes/destinations.routes';
import destinationTranslationRoutes from '../routes/destinationTranslations.routes';
import { AttractionTranslation } from '../models/AttractionTranslation';
import { Tenant } from '../models/Tenant';
import { User } from '../models/User';
import attractionRoutes from '../routes/attractions.routes';
import translationRoutes from '../routes/attractionTranslations.routes';
import pageRoutes from '../routes/page.routes';
import { translationSourceTemplate } from '../services/attractionLocalization.service';
jest.setTimeout(120000);
const app = express(); app.use(express.json()); app.use('/attractions', attractionRoutes); app.use('/translations', translationRoutes); app.use('/page', pageRoutes); app.use('/destinations', destinationRoutes); app.use('/destination-translations', destinationTranslationRoutes); app.use((error: any, _req: any, res: any, _next: any) => res.status(error.statusCode || 500).json({ error: error.message }));
const tenant = new Types.ObjectId(), other = new Types.ObjectId(), tour = new Types.ObjectId(); const sourceDate = new Date('2026-01-01T00:00:00.000Z');
const destinationId = new Types.ObjectId();
const destinationSource = { _id: destinationId, slug: 'hurghada', name: 'Hurghada', country: 'Egypt', continent: 'Africa', description: 'Beautiful Red Sea coast', shortDescription: 'Sea holidays', highlights: ['Beach'], bestTimeToVisit: 'All year', tags: ['Sea'], images: [], heroImage: 'https://images.invalid/beach.jpg', coordinates: { lat: 27, lng: 33 }, isActive: true, createdAt: sourceDate, updatedAt: sourceDate };
const destinationInput = { slug: 'hurghada-de', sourceUpdatedAt: sourceDate.toISOString(), content: { name: 'Hurghada übersetzt', country: 'Ägypten', description: '<p>Wunderschöne Küste am Roten Meer</p><script>bad()</script>', shortDescription: 'Urlaub am Meer', highlights: ['Strand'], bestTimeToVisit: 'Ganzjährig', tags: ['Meer'] } };
const destinationUrl = (locale = 'de', site = tenant) => `/destination-translations/${site}/${destinationId}/${locale}`;
async function publishDestination(locale = 'de') { const draft = (await request(app).put(destinationUrl(locale)).set(auth()).send({ ...destinationInput, slug: locale === 'de' ? 'hurghada-de' : 'hurgada' }).expect(201)).body.data; return (await request(app).post(`${destinationUrl(locale)}/transition`).set(auth()).send({ action: 'publish', expectedUpdatedAt: draft.updatedAt }).expect(200)).body.data; }
let mongo: MongoMemoryReplSet; const tokens: Record<string,string> = {};
const source = { _id: tour, slug: 'sea-cruise', pathSlug: 'sea-cruise', title: 'Sea cruise', shortDescription: 'Visit the sea', description: '<p>Travel by boat.</p>', images: ['https://images.invalid/boat.jpg'], imageAltTexts: [{ url: 'https://images.invalid/boat.jpg', alt: 'Boat' }], tenantIds: [tenant], ownerTenantId: tenant, status: 'active', category: 'cruises', destination: { city: 'Hurghada', country: 'Egypt' }, priceFrom: 49, currency: 'USD', duration: '4 hours', languages: ['en'], featured: true, pricingOptions: [{ id: 'adult', name: 'Adults', description: 'Standard ticket', price: 49, childPrice: 25, pricingModel: 'per-person', timeSlots: [{ id: 'morning', label: 'Morning', startTime: '09:00', adultPrice: 49 }] }], addons: [{ id: 'transfer', name: 'Transfer', price: 10, description: 'Hotel transfer' }], entryWindows: [{ label: 'Morning', startTime: '09:00', price: 5 }], itinerary: [{ time: '09:00', duration: '1 hour', title: 'Sail', description: 'Sail on the sea' }], gettingThere: [{ mode: 'Taxi', description: 'To the marina' }], highlights: ['Open water'], inclusions: ['Lunch'], exclusions: ['Drinks'], participantRequirements: ['Be on time'], whatToBring: ['Hat'], needToKnow: ['Bring voucher'], accessibility: ['Ask before booking'], cancellationPolicy: 'Cancel at least 24 hours before departure', meetingPoint: { address: 'Marina', instructions: 'Meet by the gate', mapUrl: 'https://maps.invalid/marina' }, seo: { metaTitle: 'Sea cruise', metaDescription: 'A sea trip' }, createdAt: sourceDate, updatedAt: sourceDate };
const input = (locale = 'de') => ({ slug: locale === 'de' ? 'meerfahrt' : 'morskaya-progulka', sourceUpdatedAt: sourceDate.toISOString(), content: { ...translationSourceTemplate(source), title: locale === 'de' ? 'Meerfahrt' : 'Морская прогулка', shortDescription: locale === 'de' ? 'Entdecken Sie das Meer' : 'Исследуйте море', description: '<p>Translated article</p><script>alert(1)</script>', pricingOptions: [{ id: 'adult', name: 'Erwachsene', description: 'Standard', timeSlots: [{ id: 'morning', label: 'Morgen' }] }], addons: [{ id: 'transfer', name: 'Transfer übersetzt', description: 'Hoteltransfer' }] } });
const url = (locale = 'de', tenantId = tenant, tourId = tour) => `/translations/${tenantId}/${tourId}/${locale}`;
const auth = (role = 'brand-admin') => ({ Authorization: `Bearer ${tokens[role]}` });
async function publish(locale = 'de') { const draft = (await request(app).put(url(locale)).set(auth()).send(input(locale)).expect(201)).body.data; return (await request(app).post(`${url(locale)}/transition`).set(auth()).send({ action: 'publish', expectedUpdatedAt: draft.updatedAt }).expect(200)).body.data; }
beforeAll(async () => { const located = spawnSync('which', ['mongod'], { encoding: 'utf8' }); const systemBinary = located.status === 0 ? located.stdout.trim() : undefined; const version = systemBinary ? spawnSync(systemBinary, ['--version'], { encoding: 'utf8' }).stdout.match(/db version v([\d.]+)/)?.[1] : undefined; mongo = await MongoMemoryReplSet.create({ replSet: { count: 1 }, binary: { version: version || '7.0.14', ...(systemBinary ? { systemBinary } : {}) } }); await mongoose.connect(mongo.getUri('tour_localization')); await Promise.all([Attraction.init(), AttractionTranslation.init(), Destination.init(), DestinationTranslation.init(), Tenant.init(), User.init()]); await Tenant.collection.insertMany([{ _id: tenant, slug: 'cruise-a', name: 'Cruise A', domain: 'cruise-a.invalid', customDomain: 'cruise-a.invalid', status: 'active' }, { _id: other, slug: 'cruise-b', name: 'Cruise B', domain: 'cruise-b.invalid', status: 'active' }]); for (const role of ['super-admin','brand-admin','manager','editor','viewer','customer','outsider']) { const _id = new Types.ObjectId(); await User.collection.insertOne({ _id, role: role === 'outsider' ? 'brand-admin' : role, status: 'active', assignedTenants: role === 'outsider' ? [other] : [tenant], email: `${role}@qa.invalid`, tokenVersion: 0 }); tokens[role] = sign({ userId: String(_id), sessionVersion: 0 }, process.env.JWT_SECRET!); } });
afterAll(async () => { await mongoose.disconnect(); await mongo?.stop(); }); beforeEach(async () => { await Attraction.collection.deleteMany({}); await AttractionTranslation.deleteMany({}); await Attraction.collection.insertOne(source); await Destination.collection.deleteMany({}); await DestinationTranslation.deleteMany({}); await Destination.collection.insertOne(destinationSource); });
it('exposes a price-free source template only to assigned staff, never a foreign tenant', async () => { await request(app).get(url()).expect(401); for (const role of ['viewer','customer','outsider']) await request(app).get(url()).set(auth(role)).expect(403); await request(app).get(url('de', other)).set(auth('super-admin')).expect(404); const value = (await request(app).get(url()).set(auth()).expect(200)).body.data; expect(value.source.content.pricingOptions[0]).not.toHaveProperty('price'); expect(value.translation).toBeNull(); expect(value.source.updatedAt).toBe(sourceDate.toISOString()); });
it('saves sanitized drafts, restricts publishing to managers and above, and never exposes drafts', async () => { const value = (await request(app).put(url()).set(auth('editor')).send(input()).expect(201)).body.data; expect(value.content.description).toBe('<p>Translated article</p>'); await request(app).post(`${url()}/transition`).set(auth('editor')).send({ action: 'publish', expectedUpdatedAt: value.updatedAt }).expect(403); const response = await request(app).get('/attractions/sea-cruise').query({ tenantId: String(tenant), locale: 'de' }).expect(200); expect(response.body.data.translationStatus).toBe('missing'); expect(response.body.data.title).toBe('Sea cruise'); expect((await request(app).get('/attractions').query({ tenantId: String(tenant), locale: 'de', pagination: 'cursor' }).expect(200)).body.data).toEqual([]); });
it('translates only presentation while preserving every price, option id and booking field', async () => { await publish(); const value = (await request(app).get('/attractions/meerfahrt').query({ tenantId: String(tenant), locale: 'de' }).expect(200)).body.data; expect(value).toMatchObject({ _id: String(tour), slug: 'sea-cruise', pathSlug: 'sea-cruise', title: 'Meerfahrt', locale: 'de', resolvedLocale: 'de', translationStatus: 'translated', localizedSlug: 'meerfahrt', currency: 'USD', priceFrom: 49, destination: source.destination, bookingTenantSlug: 'cruise-a' }); expect(value.pricingOptions[0]).toMatchObject({ id: 'adult', name: 'Erwachsene', price: 49, childPrice: 25, pricingModel: 'per-person', timeSlots: [{ id: 'morning', label: 'Morgen', startTime: '09:00', adultPrice: 49 }] }); expect(value.addons[0]).toMatchObject({ id: 'transfer', price: 10 }); expect(value.meetingPoint.mapUrl).toBe(source.meetingPoint.mapUrl); expect(value.itinerary[0].time).toBe('09:00'); expect(value.entryWindows[0].price).toBe(5); });
it('accepts any current published localized slug for language switching and projects hreflang identities', async () => { await publish(); await publish('ru'); const value = (await request(app).get('/attractions/meerfahrt').query({ tenantId: String(tenant), locale: 'ru' }).expect(200)).body.data; expect(value.title).toBe('Морская прогулка'); expect(value.localizedSlugs).toEqual({ de: 'meerfahrt', ru: 'morskaya-progulka' }); const status = (await request(app).get('/attractions/morskaya-progulka/route-status').query({ tenantId: String(tenant), locale: 'de' }).expect(200)).body.data; expect(status).toMatchObject({ slug: 'sea-cruise', translationStatus: 'translated', localizedSlug: 'meerfahrt' }); expect(status).not.toHaveProperty('description'); const sitemap = (await request(app).get('/page/sitemap/tours').query({ tenantId: String(tenant), locale: 'en' }).expect(200)).body.data; expect(sitemap.items[0].localizedSlugs).toEqual({ de: 'meerfahrt', ru: 'morskaya-progulka' }); });
it('fails closed for stale source content, unpublishing, wrong tenant and unsupported locale', async () => { const published = await publish(); await request(app).get('/attractions/meerfahrt').query({ tenantId: String(other), locale: 'de' }).expect(404); await request(app).get('/attractions/sea-cruise').query({ tenantId: String(tenant), locale: 'xx' }).expect(400); await request(app).get('/attractions/sea-cruise').query({ locale: 'de' }).expect(400); await Attraction.updateOne({ _id: tour }, { $set: { cancellationPolicy: 'New policy' } }); const response = (await request(app).get('/attractions/sea-cruise').query({ tenantId: String(tenant), locale: 'de' }).expect(200)).body.data; expect(response.translationStatus).toBe('missing'); expect(response.localizedSlugs).toEqual({}); await request(app).get('/attractions/meerfahrt').query({ tenantId: String(tenant), locale: 'de' }).expect(404); await request(app).post(`${url()}/transition`).set(auth()).send({ action: 'unpublish', expectedUpdatedAt: published.updatedAt }).expect(200); });
it('rejects money/ownership mutations, removed policy/list items, mismatched IDs and stale source versions', async () => { const value: any = input(); await request(app).put(url()).set(auth()).send({ ...value, tenantId: String(other) }).expect(400); await request(app).put(url()).set(auth()).send({ ...value, content: { ...value.content, priceFrom: 1 } }).expect(400); await request(app).put(url()).set(auth()).send({ ...value, content: { ...value.content, pricingOptions: [{ ...value.content.pricingOptions[0], price: 1 }] } }).expect(400); await request(app).put(url()).set(auth()).send({ ...value, content: { ...value.content, inclusions: [] } }).expect(400); await request(app).put(url()).set(auth()).send({ ...value, content: { ...value.content, cancellationPolicy: '' } }).expect(400); await request(app).put(url()).set(auth()).send({ ...value, sourceUpdatedAt: '2025-01-01T00:00:00.000Z' }).expect(409); await request(app).put(url()).set(auth()).send({ ...value, content: { ...value.content, pricingOptions: [{ ...value.content.pricingOptions[0], id: 'foreign' }] } }).expect(400); });
it('fences duplicate creation, concurrent editing, publication and editing a published translation', async () => { const first = await Promise.all([1,2].map(() => request(app).put(url()).set(auth()).send(input()))); expect(first.map(row => row.status).sort()).toEqual([201,409]); let current = first.find(row => row.status === 201)!.body.data; const writes = await Promise.all([1,2].map(() => request(app).put(url()).set(auth()).send({ ...input(), expectedUpdatedAt: current.updatedAt }))); expect(writes.map(row => row.status).sort()).toEqual([200,409]); current = writes.find(row => row.status === 200)!.body.data; const publishResults = await Promise.all([1,2].map(() => request(app).post(`${url()}/transition`).set(auth()).send({ action: 'publish', expectedUpdatedAt: current.updatedAt }))); expect(publishResults.map(row => row.status).sort()).toEqual([200,409]); current = publishResults.find(row => row.status === 200)!.body.data; await request(app).put(url()).set(auth()).send({ ...input(), expectedUpdatedAt: current.updatedAt }).expect(409); });
it('filters translated search in the database before reaching every cursor page and rejects cursor locale replay', async () => { for (let index=0;index<7;index++) { const id = new Types.ObjectId(); await Attraction.collection.insertOne({ ...source, _id: id, slug: `tour-${index}`, pathSlug: `tour-${index}`, priceFrom: index + 1 }); await AttractionTranslation.create({ tenantId: tenant, attractionId: id, locale: 'de', slug: `reise-${index}`, status: 'published', sourceUpdatedAt: sourceDate, content: { ...input().content, title: `Sonnenfahrt ${index}` } }); } let cursor: string | undefined; let firstCursor = ''; const seen: string[] = []; do { const response = await request(app).get('/attractions').query({ tenantId: String(tenant), locale: 'de', search: 'Sonnenfahrt', pagination: 'cursor', limit: 2, ...(cursor ? { cursor } : {}) }).expect(200); expect(response.body.pagination.total).toBe(7); seen.push(...response.body.data.map((row: any) => row._id)); cursor = response.body.pagination.nextCursor; firstCursor ||= cursor || ''; } while(cursor); expect(new Set(seen).size).toBe(7); await request(app).get('/attractions').query({ tenantId: String(tenant), locale: 'ru', search: 'Sonnenfahrt', pagination: 'cursor', limit: 2, cursor: firstCursor }).expect(400); const featured = await request(app).get('/attractions/featured').query({ tenantId: String(tenant), locale: 'de', limit: 3 }).expect(200); expect(featured.body.data).toHaveLength(3); expect(featured.body.data.every((row: any) => row.translationStatus === 'translated')).toBe(true); });

it('keeps shared-tour translations tenant-specific and never falls back to another seller', async () => { await Attraction.collection.updateOne({ _id: tour }, { $set: { tenantIds: [tenant, other] } }); await publish(); const value = (await request(app).get('/attractions/sea-cruise').query({ tenantId: String(other), locale: 'de' }).expect(200)).body.data; expect(value.translationStatus).toBe('missing'); expect(value.localizedSlugs).toEqual({}); expect(value.title).toBe('Sea cruise'); await request(app).get('/attractions/meerfahrt').query({ tenantId: String(other), locale: 'de' }).expect(404); });
it('rejects empty translations of existing information and all image descriptions', async () => { const value: any = input(); for (const content of [{ ...value.content, highlights: [''] }, { ...value.content, duration: '' }, { ...value.content, imageAltTexts: [] }, { ...value.content, meetingPoint: { instructions: '' } }]) await request(app).put(url()).set(auth()).send({ ...value, content }).expect(400); });

it('scopes destination templates and publication permissions to the site that serves it', async () => { await request(app).get(destinationUrl()).expect(401); await request(app).get(destinationUrl()).set(auth('outsider')).expect(403); await request(app).get(destinationUrl('de',other)).set(auth('super-admin')).expect(404); const draft = (await request(app).put(destinationUrl()).set(auth('editor')).send(destinationInput).expect(201)).body.data; expect(draft.content.description).toBe('<p>Wunderschöne Küste am Roten Meer</p>'); await request(app).post(`${destinationUrl()}/transition`).set(auth('editor')).send({ action: 'publish', expectedUpdatedAt: draft.updatedAt }).expect(403); const value = (await request(app).get('/destinations/hurghada').query({ tenantId: String(tenant), locale: 'de' }).expect(200)).body.data; expect(value.translationStatus).toBe('missing'); });
it('localizes destination presentation while preserving canonical filtering keys and correct tour counts', async () => { await publish(); await publishDestination(); await publishDestination('ru'); const value = (await request(app).get('/destinations/hurgada').query({ tenantId: String(tenant),locale: 'de' }).expect(200)).body.data; expect(value).toMatchObject({ name: 'Hurghada',country: 'Egypt',slug: 'hurghada',localizedName: 'Hurghada übersetzt',localizedCountry: 'Ägypten',localizedSlug: 'hurghada-de',translationStatus: 'translated',attractionCount: 1,popularAttractions: ['Meerfahrt'],priceFrom: 49,coordinates: destinationSource.coordinates }); expect(value.localizedSlugs).toEqual({ de: 'hurghada-de',ru: 'hurgada' }); const list = (await request(app).get('/destinations').query({ tenantId: String(tenant),locale: 'de',search: 'Ägypten' }).expect(200)).body; expect(list.data).toHaveLength(1); expect(list.pagination.total).toBe(1); const featured = (await request(app).get('/destinations/featured').query({ tenantId: String(tenant),locale: 'de' }).expect(200)).body.data; expect(featured[0].localizedName).toBe('Hurghada übersetzt'); });
it('excludes stale destination translations and never uses another site overlay', async () => { await publishDestination(); await request(app).get('/destinations/hurghada-de').query({ tenantId: String(other),locale: 'de' }).expect(404); await Destination.updateOne({ _id: destinationId },{ $set: { shortDescription: 'Updated destination' } }); const value = (await request(app).get('/destinations/hurghada').query({ tenantId: String(tenant),locale: 'de' }).expect(200)).body.data; expect(value.translationStatus).toBe('missing'); expect(value.localizedSlugs).toEqual({}); expect((await request(app).get('/destinations').query({ tenantId: String(tenant),locale: 'de' }).expect(200)).body.data).toEqual([]); });
it('fences destination duplicate saves, stale edits, published edits and unsafe field injection', async () => { const results = await Promise.all([1,2].map(() => request(app).put(destinationUrl()).set(auth()).send(destinationInput))); expect(results.map(row => row.status).sort()).toEqual([201,409]); const draft = results.find(row => row.status === 201)!.body.data; const edits = await Promise.all([1,2].map(() => request(app).put(destinationUrl()).set(auth()).send({ ...destinationInput,expectedUpdatedAt: draft.updatedAt }))); expect(edits.map(row => row.status).sort()).toEqual([200,409]); let current = edits.find(row => row.status === 200)!.body.data; current = (await request(app).post(`${destinationUrl()}/transition`).set(auth()).send({ action: 'publish',expectedUpdatedAt: current.updatedAt }).expect(200)).body.data; await request(app).put(destinationUrl()).set(auth()).send({ ...destinationInput,expectedUpdatedAt: current.updatedAt }).expect(409); current = (await request(app).post(`${destinationUrl()}/transition`).set(auth()).send({ action: 'unpublish',expectedUpdatedAt: current.updatedAt }).expect(200)).body.data; expect(current.status).toBe('draft'); await request(app).put(destinationUrl()).set(auth()).send({ ...destinationInput,expectedUpdatedAt: current.updatedAt,content: { ...destinationInput.content,coordinates: { lat: 0,lng: 0 } } }).expect(400); await request(app).put(destinationUrl()).set(auth()).send({ ...destinationInput,expectedUpdatedAt: current.updatedAt,content: { ...destinationInput.content,highlights: [] } }).expect(400); });

const sourceExport = { tenantId: String(tenant),tenantSlug:'cruise-a',domain:'cruise-a.invalid',tours:[{id:String(tour),sourceUpdatedAt:sourceDate.toISOString()}],destinations:[{id:String(destinationId),sourceUpdatedAt:sourceDate.toISOString()}] };
const migrationPayload = () => ({ ...sourceExport,sourceSha256:'a'.repeat(64),tours:['de','ru'].map(locale=>({id:String(tour),locale,...input(locale)})),destinations:['de','ru'].map(locale=>({id:String(destinationId),locale,...destinationInput,slug:locale==='de'?'hurghada-de':'hurgada'})) });
it('dry-runs without writes, applies atomically, supports idempotent replay and removes only its rows on rollback',async()=>{ const plan=await planLocalization(sourceExport,migrationPayload(),'a'.repeat(64)); expect(await AttractionTranslation.countDocuments({})).toBe(0); expect(await DestinationTranslation.countDocuments({})).toBe(0); const persisted=mongoose.mongo.BSON.EJSON.parse(mongoose.mongo.BSON.EJSON.stringify(plan,{relaxed:false})); expect(await executeLocalizationPlan(persisted,plan.digest,'apply')).toMatchObject({changed:true,verified:true,rows:4}); expect(await AttractionTranslation.countDocuments({status:'published'})).toBe(2); expect(await executeLocalizationPlan(persisted,plan.digest,'apply')).toMatchObject({changed:false}); expect(await executeLocalizationPlan(persisted,plan.digest,'rollback')).toMatchObject({changed:true}); expect(await AttractionTranslation.countDocuments({})).toBe(0); expect(await DestinationTranslation.countDocuments({})).toBe(0); expect(await executeLocalizationPlan(persisted,plan.digest,'rollback')).toMatchObject({changed:false}); });
it('backs up and restores exact pre-existing translation data including unknown future fields',async()=>{ const before={_id:new Types.ObjectId(),tenantId:tenant,attractionId:tour,locale:'de',slug:'old-translation',status:'draft',sourceUpdatedAt:sourceDate,content:input().content,createdAt:sourceDate,updatedAt:sourceDate,retainedField:{value:'preserve'}}; await AttractionTranslation.collection.insertOne(before); const plan=await planLocalization(sourceExport,migrationPayload(),'a'.repeat(64)); await executeLocalizationPlan(plan,plan.digest,'apply'); await executeLocalizationPlan(plan,plan.digest,'rollback'); expect(localizationDigest(await AttractionTranslation.collection.findOne({_id:before._id}))).toBe(localizationDigest(before)); });
it('rejects wrong source fingerprints, incomplete language sets, modified plans and changed live sources',async()=>{ await expect(planLocalization(sourceExport,migrationPayload(),'b'.repeat(64))).rejects.toThrow('digest'); const missing=migrationPayload(); missing.tours.pop(); await expect(planLocalization(sourceExport,missing,'a'.repeat(64))).rejects.toThrow('Both languages'); const plan=await planLocalization(sourceExport,migrationPayload(),'a'.repeat(64)); await expect(executeLocalizationPlan({...plan,domain:'foreign.invalid'},plan.digest,'apply')).rejects.toThrow('digest'); await Attraction.updateOne({_id:tour},{$set:{title:'Changed source'}}); await expect(executeLocalizationPlan(plan,plan.digest,'apply')).rejects.toThrow('Source changed'); expect(await AttractionTranslation.countDocuments({})).toBe(0); });
it('refuses to overwrite another editor during apply or rollback',async()=>{ let plan=await planLocalization(sourceExport,migrationPayload(),'a'.repeat(64)); await AttractionTranslation.create({tenantId:tenant,attractionId:tour,locale:'de',slug:'editor-draft',status:'draft',sourceUpdatedAt:sourceDate,content:input().content}); await expect(executeLocalizationPlan(plan,plan.digest,'apply')).rejects.toThrow('rows changed'); plan=await planLocalization(sourceExport,migrationPayload(),'a'.repeat(64)); await executeLocalizationPlan(plan,plan.digest,'apply'); await AttractionTranslation.collection.updateOne({tenantId:tenant,attractionId:tour,locale:'de'},{$set:{externalEdit:true}}); await expect(executeLocalizationPlan(plan,plan.digest,'rollback')).rejects.toThrow('rows changed'); expect(await DestinationTranslation.countDocuments({})).toBe(2); });
it('rolls back all database effects if any write fails inside the transaction',async()=>{ const plan=await planLocalization(sourceExport,migrationPayload(),'a'.repeat(64)); const failure=jest.spyOn(DestinationTranslation.collection,'replaceOne').mockRejectedValueOnce(new Error('Temporary failure')); try{await expect(executeLocalizationPlan(plan,plan.digest,'apply')).rejects.toThrow('Temporary failure');}finally{failure.mockRestore();} expect(await AttractionTranslation.countDocuments({})).toBe(0); expect(await DestinationTranslation.countDocuments({})).toBe(0); });

it('keeps published translations current after price, stock, rating and sort changes but invalidates every presentation source change',async()=>{
  await publish(); await publishDestination();
  await Attraction.updateOne({_id:tour},{$set:{priceFrom:75,'pricingOptions.0.price':75,'pricingOptions.0.timeSlots.0.adultPrice':75,'pricingOptions.0.maxParticipants':12,rating:4.9,sortOrder:99,totalReviews:7}});
  await Destination.updateOne({_id:destinationId},{$set:{sortOrder:9}});
  const query={tenantId:String(tenant),locale:'de'};
  const detail=(await request(app).get('/attractions/meerfahrt').query(query).expect(200)).body.data;
  expect(detail).toMatchObject({translationStatus:'translated',priceFrom:75}); expect(detail.pricingOptions[0].price).toBe(75); expect(detail.pricingOptions[0].maxParticipants).toBe(12);
  expect((await request(app).get('/attractions').query({...query,search:'Meerfahrt'}).expect(200)).body.data).toHaveLength(1);
  expect((await request(app).get('/attractions/meerfahrt/route-status').query(query).expect(200)).body.data.translationStatus).toBe('translated');
  expect((await request(app).get(destinationUrl()).set(auth()).expect(200)).body.data.stale).toBe(false);
  expect((await request(app).get(url()).set(auth()).expect(200)).body.data.stale).toBe(false);
  const original=await Attraction.findById(tour).lean();
  for(const [field,value] of Object.entries({cancellationPolicy:'New policy','pricingOptions.0.name':'New label','pricingOptions.0.id':'replacement-id','pricingOptions.0.timeSlots.0.label':'Evening',inclusions:['Different inclusion'],'meetingPoint.instructions':'New gate','imageAltTexts.0.alt':'New description','seo.metaTitle':'New search title','itinerary.0.duration':'Two hours',participantRequirements:['Different condition']})) {
    await Attraction.collection.updateOne({_id:tour},{$set:{[field]:value}});
    expect((await request(app).get('/attractions/sea-cruise').query(query).expect(200)).body.data.translationStatus).toBe('missing');
    expect((await request(app).get('/attractions').query(query).expect(200)).body.data).toEqual([]);
    await request(app).get('/attractions/meerfahrt').query(query).expect(404);
    await Attraction.collection.replaceOne({_id:tour},original as any);
  }
});
it('allows publishing a reviewed draft after operational updates and fences changed copy without timestamp changes',async()=>{
  const draft=(await request(app).put(url()).set(auth()).send(input()).expect(201)).body.data;
  await Attraction.updateOne({_id:tour},{$set:{priceFrom:60}});
  await request(app).post(`${url()}/transition`).set(auth()).send({action:'publish',expectedUpdatedAt:draft.updatedAt}).expect(200);
  const legacyId=new Types.ObjectId(); await Attraction.collection.insertOne({...source,_id:legacyId,slug:'legacy',pathSlug:'legacy'});
  await AttractionTranslation.create({tenantId:tenant,attractionId:legacyId,locale:'de',slug:'alt',status:'published',sourceUpdatedAt:sourceDate,content:input().content});
  expect((await request(app).get('/attractions/legacy').query({tenantId:String(tenant),locale:'de'}).expect(200)).body.data.translationStatus).toBe('translated');
  await Attraction.updateOne({_id:legacyId},{$set:{priceFrom:60}});
  expect((await request(app).get('/attractions/legacy').query({tenantId:String(tenant),locale:'de'}).expect(200)).body.data.translationStatus).toBe('missing');
});
it('resolves requested-language aliases before native slugs, English native slugs first and other aliases only as fallback',async()=>{
  await publish(); await publish('ru'); const second=new Types.ObjectId();
  await Attraction.collection.insertOne({...source,_id:second,slug:'meerfahrt',pathSlug:'meerfahrt',title:'Other native tour'});
  for(const path of ['/attractions/meerfahrt','/attractions/meerfahrt/route-status']) {
    expect((await request(app).get(path).query({tenantId:String(tenant),locale:'de'}).expect(200)).body.data._id).toBe(String(tour));
    expect((await request(app).get(path).query({tenantId:String(tenant),locale:'en'}).expect(200)).body.data._id).toBe(String(second));
    expect((await request(app).get(path).query({tenantId:String(tenant),locale:'ru'}).expect(200)).body.data._id).toBe(String(second));
  }
  expect((await request(app).get('/attractions/morskaya-progulka').query({tenantId:String(tenant),locale:'de'}).expect(200)).body.data._id).toBe(String(tour));
});

it('matches literal punctuation in translated destination searches without interpreting regex operators',async()=>{
  const content={...destinationInput.content,name:'Bucht (Ost) + Strand',shortDescription:'Sonne . Wasser'};
  const draft=(await request(app).put(destinationUrl()).set(auth()).send({...destinationInput,content}).expect(201)).body.data;
  await request(app).post(`${destinationUrl()}/transition`).set(auth()).send({action:'publish',expectedUpdatedAt:draft.updatedAt}).expect(200);
  for(const search of ['Bucht (Ost)','+ Strand','Sonne . Wasser']) {
    const response=await request(app).get('/destinations').query({tenantId:String(tenant),locale:'de',search}).expect(200);
    expect(response.body.pagination.total).toBe(1); expect(response.body.data[0].localizedName).toBe(content.name);
  }
  const response=await request(app).get('/destinations').query({tenantId:String(tenant),locale:'de',search:'.*'}).expect(200);
  expect(response.body.data).toEqual([]); expect(response.body.pagination.total).toBe(0);
});
it('requires complete identity and slug uniqueness indexes before applying or rolling back a migration',async()=>{
  const plan=await planLocalization(sourceExport,migrationPayload(),'a'.repeat(64));
  for(const model of [AttractionTranslation,DestinationTranslation]) {
    const actual=await model.collection.indexes();
    const slugIndex=actual.find(index=>index.unique&&index.key.slug===1)!;
    const identityIndex=actual.find(index=>index.unique&&index.key.slug===undefined)!;
    for(const invalid of [
      actual.filter(index=>index!==slugIndex),
      actual.filter(index=>index!==identityIndex),
      actual.map(index=>index===slugIndex?{...index,partialFilterExpression:{status:'published'}}:index),
      actual.map(index=>index===slugIndex?{...index,sparse:true}:index),
      actual.map(index=>index===identityIndex?{...index,key:{...index.key,extra:1}}:index),
      actual.map(index=>index===slugIndex?{...index,collation:{locale:'en',strength:2}}:index),
    ]) {
      const spy=jest.spyOn(model.collection,'indexes').mockResolvedValue(invalid as any);
      try { for(const mode of ['apply','rollback'] as const) await expect(executeLocalizationPlan(plan,plan.digest,mode)).rejects.toThrow('identity and URL uniqueness indexes'); }
      finally {spy.mockRestore();}
      expect(await AttractionTranslation.countDocuments({})).toBe(0); expect(await DestinationTranslation.countDocuments({})).toBe(0);
    }
  }
});
