import express from 'express';
import request from 'supertest';
import mongoose,{Types} from 'mongoose';
import {spawnSync} from 'child_process';
import {MongoMemoryReplSet} from 'mongodb-memory-server';
import bookingRoutes from '../routes/bookings.routes';
import userRoutes from '../routes/users.routes';
import {Tenant} from '../models/Tenant';
import {Attraction} from '../models/Attraction';
import {Booking} from '../models/Booking';
import {User} from '../models/User';
jest.mock('../middleware/auth.middleware',()=>({ ...jest.requireActual('../middleware/auth.middleware'),authenticate:(req:any,res:any,next:any)=>{const id=req.header('x-customer');if(!id)return res.status(401).json({success:false});req.user={_id:new Types.ObjectId(id),role:'customer'};next();} }));
jest.setTimeout(120000);
const owner=new Types.ObjectId(),other=new Types.ObjectId(),customer=new Types.ObjectId(),foreignCustomer=new Types.ObjectId();
const app=express();app.use(express.json());app.use('/bookings',bookingRoutes);app.use('/users',userRoutes);app.use((error:any,_req:any,res:any,_next:any)=>res.status(error.statusCode || 500).json({success:false,error:error.message}));
let mongo:MongoMemoryReplSet;
beforeAll(async()=>{const binary=spawnSync('which',['mongod'],{encoding:'utf8'}).stdout.trim();const version=binary?spawnSync(binary,['--version'],{encoding:'utf8'}).stdout.match(/db version v([\d.]+)/)?.[1]:undefined;mongo=await MongoMemoryReplSet.create({replSet:{count:1},binary:{version:version || '7.0.14',...(binary?{systemBinary:binary}:{})}});await mongoose.connect(mongo.getUri('customer_lists'));});
afterAll(async()=>{await mongoose.disconnect();await mongo?.stop();});
beforeEach(async()=>{await Promise.all([Tenant.collection.deleteMany({}),Attraction.collection.deleteMany({}),Booking.collection.deleteMany({}),User.collection.deleteMany({})]);await Tenant.collection.insertMany([owner,other].map((_id,i)=>({_id,slug:`qa-site-${i}`,status:'active',name:'QA site',domain:`qa-site-${i}.invalid`})));});
afterEach(()=>jest.restoreAllMocks());
const getBookings=(query:Record<string,unknown>={},user=customer,site=owner)=>request(app).get('/bookings/my').set('x-customer',String(user)).query({tenantId:String(site),pagination:'cursor',limit:20,...query});
const getSaved=(query:Record<string,unknown>={},user=customer,site=owner)=>request(app).get('/users/wishlist').set('x-customer',String(user)).query({tenantId:String(site),pagination:'cursor',limit:20,...query});
async function seed(count=103){const tours=Array.from({length:count},(_,i)=>({_id:new Types.ObjectId(),slug:`trip-${i}`,title:i===count-1?'Unique tail trip':`Trip ${i}`,tenantIds:[owner],status:'active',images:[],priceFrom:40,currency:'EUR',createdAt:new Date('2026-01-01')}));await Attraction.collection.insertMany(tours);await User.collection.insertMany([{_id:customer,email:'qa-one@example.invalid',wishlist:tours.map(row=>row._id)},{_id:foreignCustomer,email:'qa-two@example.invalid',wishlist:[]}]);await Booking.collection.insertMany(tours.map((tour,i)=>({_id:new Types.ObjectId(),reference:`REF-${i}`,userId:customer,tenantId:owner,attractionId:tour._id,status:i%2?'confirmed':'completed',total:40,currency:'EUR',createdAt:new Date('2026-01-01')})));return tours;}
it('reaches every booking beyond51 and saved item beyond101, with stable backward cursors',async()=>{await seed();for(const get of [getBookings,getSaved]){let cursor:string|undefined;const pages:any[]=[];do{const body=(await get({cursor}).expect(200)).body;pages.push(body);cursor=body.pagination.nextCursor || undefined;}while(cursor);const rows=pages.flatMap(page=>page.data);expect(rows).toHaveLength(103);expect(new Set(rows.map(row=>row._id)).size).toBe(103);expect(pages[0].pagination.total).toBe(103);expect(pages.at(-1).pagination.nextCursor).toBeNull();const previous=(await get({cursor:pages[2].pagination.previousCursor}).expect(200)).body;expect(previous.data.map((row:any)=>row._id)).toEqual(pages[1].data.map((row:any)=>row._id));}});
it('server search reaches tail and status/counts cover all bookings rather than a page',async()=>{await seed();const searched=(await getBookings({search:'Unique tail'}).expect(200)).body;expect(searched.data).toHaveLength(1);expect(searched.data[0].reference).toBe('REF-102');const confirmed=(await getBookings({status:'confirmed'}).expect(200)).body;expect(confirmed.pagination.total).toBe(51);expect(confirmed.counts).toMatchObject({all:103,confirmed:51,completed:52});expect(confirmed.data.every((row:any)=>row.status==='confirmed')).toBe(true);expect((await getSaved({search:'Unique tail'}).expect(200)).body.data.map((row:any)=>row.slug)).toEqual(['trip-102']);});
it('binds cursors to owner, site and filters, rejects malformed scope/limits and requires authentication',async()=>{await seed();const first=(await getBookings().expect(200)).body;for(const next of [getBookings({cursor:first.pagination.nextCursor},foreignCustomer),getBookings({cursor:first.pagination.nextCursor},customer,other),getBookings({cursor:first.pagination.nextCursor,search:'Trip'}),getBookings({cursor:first.pagination.nextCursor,status:'confirmed'}),getBookings({cursor:'bad'}),getBookings({limit:101}),getBookings({status:'hostile'})])await next.expect(400);await request(app).get('/bookings/my').expect(401);await request(app).get('/users/wishlist').expect(401);expect((await getBookings({},foreignCustomer).expect(200)).body.data).toEqual([]);expect((await getBookings({},customer,other).expect(200)).body.data).toEqual([]);await getSaved({},customer,new Types.ObjectId()).expect(404);});
it('concurrent insertion before the first cursor does not repeat or drop the original tail',async()=>{const tours=await seed(57);const first=(await getBookings().expect(200)).body;await Booking.collection.insertOne({_id:new Types.ObjectId(),reference:'NEW',userId:customer,tenantId:owner,attractionId:tours[0]._id,status:'confirmed',createdAt:new Date('2026-02-01')});let cursor=first.pagination.nextCursor;const rows=[...first.data];while(cursor){const body=(await getBookings({cursor}).expect(200)).body;rows.push(...body.data);cursor=body.pagination.nextCursor;}expect(rows).toHaveLength(57);expect(new Set(rows.map(row=>row._id)).size).toBe(57);expect(rows.some(row=>row.reference==='NEW')).toBe(false);});
it('fails closed on a malformed booking attraction join and wishlist never emits foreign/archive/trash records',async()=>{const tours=await seed();await Attraction.collection.updateOne({_id:tours[0]._id},{$set:{tenantIds:[other]}});await getBookings().expect(409);await Attraction.collection.updateOne({_id:tours[1]._id},{$set:{archivedAt:new Date()}});await Attraction.collection.updateOne({_id:tours[2]._id},{$set:{trashedAt:new Date()}});const saved=(await getSaved().expect(200)).body;expect(saved.pagination.total).toBe(100);expect(saved.data.every((row:any)=>!['trip-0','trip-1','trip-2'].includes(row.slug))).toBe(true);});
it('bounded page removal is atomic, owner/site scoped and preserves the tail and other-site entries',async()=>{const tours=await seed();const foreign=new Types.ObjectId();await Attraction.collection.insertOne({_id:foreign,slug:'foreign',status:'active',tenantIds:[other]});await User.updateOne({_id:customer},{$push:{wishlist:foreign}});const remove=(ids:string[],user=customer)=>request(app).delete('/users/wishlist/page').set('x-customer',String(user)).query({tenantId:String(owner)}).send({ids});await remove([String(tours[0]._id),String(foreign)]).expect(409);expect((await User.findById(customer).lean())?.wishlist).toHaveLength(104);await remove(Array.from({length:101},()=>String(tours[0]._id))).expect(400);await remove(['bad']).expect(400);await remove([String(tours[0]._id)],foreignCustomer).expect(409);await remove(tours.slice(0,20).map(row=>String(row._id))).expect(200);const user=await User.findById(customer).lean();expect(user?.wishlist).toHaveLength(84);expect(user?.wishlist.map(String)).toContain(String(foreign));expect((await getSaved().expect(200)).body.pagination.total).toBe(83);});
it('legacy page clients retain shape and validated status is no longer stripped',async()=>{await seed(57);const response=await request(app).get('/bookings/my').set('x-customer',String(customer)).query({page:2,limit:10,status:'confirmed'}).expect(200);expect(response.body.pagination).toMatchObject({page:2,limit:10,total:28,totalPages:3});expect(response.body.data.every((row:any)=>row.status==='confirmed')).toBe(true);const saved=await request(app).get('/users/wishlist').set('x-customer',String(customer)).expect(200);expect(Array.isArray(saved.body.data)).toBe(true);expect(saved.body.pagination).toBeUndefined();});
it('database failure is an error, and repeat read succeeds without mutation',async()=>{await seed(3);const spy=jest.spyOn(Booking,'aggregate').mockRejectedValueOnce(new Error('Unavailable'));await getBookings().expect(500);spy.mockRestore();expect((await getBookings().expect(200)).body.pagination.total).toBe(3);});

it('preserves a customer’s verified reseller booking while denying a fabricated supplier join',async()=>{const tours=await seed(1);await Attraction.collection.updateOne({_id:tours[0]._id},{$set:{tenantIds:[other],ownerTenantId:other}});await Booking.collection.updateOne({userId:customer},{$set:{isResale:true,supplierTenantId:other,sellerTenantId:owner}});expect((await getBookings().expect(200)).body.data).toHaveLength(1);await Booking.collection.updateOne({userId:customer},{$set:{supplierTenantId:owner}});await getBookings().expect(409);});

it('search is literal and bounded, never a regex widening or pathological expression',async()=>{await seed(3);expect((await getBookings({search:'.*'}).expect(200)).body.pagination.total).toBe(0);expect((await getSaved({search:'.*'}).expect(200)).body.pagination.total).toBe(0);await getBookings({search:'a'.repeat(500)}).expect(400);});
