import express from 'express';
import request from '../test/loopbackRequest';
import {authenticate,optionalAuth} from '../middleware/auth.middleware';
import {expectedPrincipal} from '../middleware/expected-principal';
import {refreshToken} from '../controllers/auth.controller';
import {User} from '../models/User';
import {verifyToken,verifyRefreshToken,generateRefreshToken} from '../utils/jwt';
import {hashToken} from '../utils/hash';
jest.mock('../models/User',()=>({User:{findById:jest.fn()}}));
jest.mock('../utils/jwt',()=>({verifyToken:jest.fn(),verifyRefreshToken:jest.fn(),generateAccessToken:jest.fn(()=> 'new-access'),generateRefreshToken:jest.fn(()=> 'new-refresh')}));
jest.mock('../services/email.service',()=>({sendPasswordChangedEmail:jest.fn(),sendPasswordResetEmail:jest.fn(),sendWelcomeEmail:jest.fn()}));
jest.mock('../services/notification.service',()=>({createAdminNotifications:jest.fn()}));
const owner='123456789012345678901234',other='223456789012345678901234';
it('accepts absent legacy header containers but rejects an unparsed raw assertion',()=>{
 expect(expectedPrincipal({headers:undefined,rawHeaders:undefined} as never)).toEqual({valid:true});
 expect(expectedPrincipal({headers:undefined,rawHeaders:['X-Expected-Principal',owner]} as never)).toEqual({valid:false});
});
const user={_id:owner,status:'active',tokenVersion:1,refreshToken:hashToken('old-refresh'),save:jest.fn()};
const app=express();app.use((req,_res,next)=>{(req as unknown as {cookies:unknown}).cookies={accessToken:'access',refreshToken:'old-refresh'};next();});app.get('/required',authenticate,(_req,res)=>res.json({ok:true}));app.get('/optional',optionalAuth,(req,res)=>res.json({owner:(req as unknown as {user?:typeof user}).user?._id || null}));app.post('/refresh',refreshToken);
beforeEach(()=>{jest.clearAllMocks();(verifyToken as jest.Mock).mockReturnValue({userId:owner,sessionVersion:1});(verifyRefreshToken as jest.Mock).mockReturnValue({userId:owner,sessionVersion:1});(User.findById as jest.Mock).mockReturnValue(Object.assign(Promise.resolve(user),{select:()=>Promise.resolve(user)}));user.refreshToken=hashToken('old-refresh');});
it.each(['/required','/optional'])('keeps legacy %s and matching authenticated principal',async path=>{expect((await request(app).get(path)).status).toBe(200);expect((await request(app).get(path).set('X-Expected-Principal',owner)).status).toBe(200);});
it.each(['/required','/optional'])('denies other account or anonymous assertion before effects %s',async path=>{expect((await request(app).get(path).set('X-Expected-Principal',other)).status).toBe(409);expect((await request(app).get(path).set('X-Expected-Principal','anonymous')).status).toBe(409);});
it.each(['','account-id',`${owner},${owner}`,`${owner} `])('rejects malformed assertion %s',async value=>{expect(expectedPrincipal({headers:{'x-expected-principal':value},rawHeaders:[]})).toEqual({valid:false});});
it('rejects duplicate/array assertions even when their values match',()=>{expect(expectedPrincipal({headers:{'x-expected-principal':owner},rawHeaders:['X-Expected-Principal',owner,'x-expected-principal',owner]}).valid).toBe(false);expect(expectedPrincipal({headers:{'x-expected-principal':[owner,owner]},rawHeaders:[]}).valid).toBe(false);});
it('optional authenticated assertion never degrades expired token into guest, while anonymous and legacy do',async()=>{(verifyToken as jest.Mock).mockImplementation(()=>{throw Error('expired');});expect((await request(app).get('/optional').set('X-Expected-Principal',owner)).status).toBe(409);expect((await request(app).get('/optional').set('X-Expected-Principal','anonymous')).status).toBe(200);expect((await request(app).get('/optional')).status).toBe(200);});
it.each([other,'anonymous','bad'])('refresh denial does not rotate or persist tokens: %s',async value=>{expect((await request(app).post('/refresh').set('X-Expected-Principal',value)).status).toBe(value==='bad'?400:409);expect(user.save).not.toHaveBeenCalled();expect(generateRefreshToken).not.toHaveBeenCalled();});
it('refresh preserves matching and absent-header legacy contracts',async()=>{expect((await request(app).post('/refresh').set('X-Expected-Principal',owner)).status).toBe(200);expect(user.save).toHaveBeenCalledTimes(1);user.refreshToken=hashToken('old-refresh');expect((await request(app).post('/refresh')).status).toBe(200);});
it('matching assertion does not bypass revoked/disabled accounts',async()=>{(verifyToken as jest.Mock).mockReturnValue({userId:owner,sessionVersion:0});expect((await request(app).get('/required').set('X-Expected-Principal',owner)).status).toBe(401);expect((await request(app).get('/optional').set('X-Expected-Principal',owner)).status).toBe(409);});
