import express from 'express';
import request from '../test/loopbackRequest';
import mongoose, { Types } from 'mongoose';
import { spawnSync } from 'child_process';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import attractionRoutes from '../routes/attractions.routes';
import destinationRoutes from '../routes/destinations.routes';
import { Tenant } from '../models/Tenant';
import { Attraction } from '../models/Attraction';
import { Destination } from '../models/Destination';
import { DestinationTranslation } from '../models/DestinationTranslation';
import { AttractionTranslation } from '../models/AttractionTranslation';
import { SpecialOffer } from '../models/SpecialOffer';
jest.mock('../middleware/auth.middleware', () => ({ ...jest.requireActual('../middleware/auth.middleware'), optionalAuth: (_req: any, _res: any, next: any) => next() }));
jest.setTimeout(120000);
const owner = new Types.ObjectId(), foreign = new Types.ObjectId();
const app = express(); app.use('/attractions', attractionRoutes); app.use('/destinations', destinationRoutes);
app.use((error: any, _req: any, res: any, _next: any) => res.status(error.statusCode || 500).json({ success: false, error: error.message }));
let mongo: MongoMemoryReplSet;
beforeAll(async () => { const binary = spawnSync('which', ['mongod'], { encoding: 'utf8' }).stdout.trim(); const version = binary ? spawnSync(binary, ['--version'], { encoding: 'utf8' }).stdout.match(/db version v([\d.]+)/)?.[1] : undefined; mongo = await MongoMemoryReplSet.create({ replSet: { count: 1 }, binary: { version: version || '7.0.14', ...(binary ? { systemBinary: binary } : {}) } }); await mongoose.connect(mongo.getUri('horse_catalogue_cursor')); });
afterAll(async () => { await mongoose.disconnect(); await mongo?.stop(); });
beforeEach(async () => { for (const model of [Attraction, Destination, SpecialOffer, Tenant, DestinationTranslation, AttractionTranslation]) await model.collection.deleteMany({}); await Tenant.collection.insertMany([owner, foreign].map((_id, i) => ({ _id, slug: `qa-cursor-${i}`, domain: `qa-cursor-${i}.invalid`, name: 'QA catalogue', status: 'active' }))); });
afterEach(() => jest.restoreAllMocks());
const tour = (slug: string, extra: object = {}) => ({ _id: new Types.ObjectId(), slug, title: slug, category: 'tours', destination: { city: slug, country: 'Egypt' }, status: 'active', tenantIds: [owner], images: [], currency: 'EUR', priceFrom: 80, pricingOptions: [{ name: 'Adult', price: 80, originalPrice: 100 }], createdAt: new Date(), ...extra });
const destination = (name: string, extra: object = {}) => ({ _id: new Types.ObjectId(), slug: name.toLowerCase(), name, country: 'Egypt', continent: 'Africa', isActive: true, sortOrder: 0, ...extra });
const offer = (attractionId: Types.ObjectId, extra: object = {}) => ({ attractionId, title: 'Offer', discountType: 'percentage', discountValue: 10, validFrom: new Date(Date.now() - 100000), validUntil: new Date(Date.now() + 100000), isActive: true, usageCount: 0, usageLimit: 100, ...extra });
const get = (path: string, query: object = {}, site: Types.ObjectId = owner) => request(app).get(path).query({ tenantId: String(site), pagination: 'cursor', limit: 7, ...query });
it('destinations reach the DB tail and reverse with accurate scope/count/search', async () => {
 const rows = Array.from({ length: 57 }, (_, i) => destination(`Port${i}`, { sortOrder: i })); await Destination.collection.insertMany(rows); await Attraction.collection.insertMany(rows.map(row => tour(row.name))); await Destination.collection.insertMany([destination('Foreign'), destination('Inactive', { isActive: false }), destination('Draft'), destination('Archived')]); await Attraction.collection.insertMany([tour('Foreign', { tenantIds: [foreign] }), tour('Inactive'), tour('Draft', { status: 'draft' }), tour('Archived', { archivedAt: new Date() })]);
 let cursor: string | undefined; const names: string[] = []; let last: any;
 do { last = (await get('/destinations', { cursor }).expect(200)).body; expect(last.pagination.total).toBe(57); names.push(...last.data.map((row: any) => row.name)); cursor = last.pagination.nextCursor || undefined; } while (cursor);
 expect(names).toEqual(rows.map(row => row.name)); expect(last.data[0].attractionCount).toBe(1); const previous = (await get('/destinations', { cursor: last.pagination.previousCursor }).expect(200)).body; expect(previous.data.map((row: any) => row.name)).toEqual(rows.slice(49, 56).map(row => row.name));
 const search = (await get('/destinations', { search: 'Port56' }).expect(200)).body; expect(search.pagination.total).toBe(1); expect(search.data[0].name).toBe('Port56');
 const first = (await get('/destinations').expect(200)).body; await get('/destinations', { cursor: first.pagination.nextCursor, search: 'Port' }).expect(400); await get('/destinations', { cursor: first.pagination.nextCursor }, foreign).expect(400);
});
it('destinations require explicit public tenant and reject editor/admin/invalid inputs', async () => { await request(app).get('/destinations').query({ pagination: 'cursor' }).expect(400); for (const q of [{ scope: 'admin' }, { forEditor: 'true' }, { limit: 101 }, { cursor: '!' }, { 'search[$ne]': 'x' }, { locale: 'es' }]) await get('/destinations', q).expect(400); });
it('pickup areas count only this site public pickup tours and hide unused areas', async () => { await Tenant.collection.updateOne({ _id: owner }, { $set: { designMode: 'nautical', pickupDestinationSlugs: ['pickup'] } }); await Destination.collection.insertMany([destination('Pickup'), destination('Unused'), destination('Own')]); await Attraction.collection.insertMany([tour('Own', { hasHotelPickup: true }), tour('Foreign', { hasHotelPickup: true, tenantIds: [foreign] }), tour('Draft', { hasHotelPickup: true, status: 'draft' })]); const body = (await get('/destinations').expect(200)).body; expect(body.pagination.total).toBe(2); expect(body.data.find((row: any) => row.slug === 'pickup')).toMatchObject({ attractionCount: 1, servedByPickup: true }); });
it('destination source fallback preserves canonical names and locale/count isolation', async () => { await Destination.collection.insertOne(destination('Port')); await Attraction.collection.insertOne(tour('Port')); const body = (await get('/destinations', { locale: 'ar', localeFallback: 'source' }).expect(200)).body; expect(body.data[0]).toMatchObject({ name: 'Port', resolvedLocale: 'en', translationStatus: 'missing', attractionCount: 1 }); const noCounts = (await get('/destinations', { includeCount: 'false' }).expect(200)).body; expect(noCounts.data[0].attractionCount).toBeUndefined(); });
it('deal cursor reaches last page, binds filters, preserves legacy DTO and raw money', async () => { const rows = Array.from({ length: 57 }, (_, i) => tour(`deal-${i}`, { priceFrom: 80 + i, pricingOptions: [{ price: 80 + i, originalPrice: 100 + i }] })); await Attraction.collection.insertMany(rows); let cursor: string | undefined; const ids: string[] = []; do { const body = (await get('/attractions', { deals: 'true', sort: 'price-low', cursor }).expect(200)).body; expect(body.pagination.total).toBe(57); body.data.forEach((row: any) => { ids.push(row.slug); expect(row.publicDeal.price).toBe(row.priceFrom); expect(row.pricingOptions[0].price).toBe(row.priceFrom); expect(row.publicDeal.source).toBe('was-price'); }); cursor = body.pagination.nextCursor || undefined; } while (cursor); expect(ids).toEqual(rows.map(row => row.slug)); const first = (await get('/attractions', { deals: 'true' }).expect(200)).body; await get('/attractions', { cursor: first.pagination.nextCursor }).expect(400); await get('/attractions', { deals: 'true', cursor: first.pagination.nextCursor, search: 'deal' }).expect(400); expect((await get('/attractions', { search: 'deal-56', deals: 'true' }).expect(200)).body.pagination.total).toBe(1); expect((await get('/attractions').expect(200)).body.data[0].publicDeal).toBeUndefined(); });
it('offer eligibility matches currency/dates/usage and checkout priority, never raw public offer leakage', async () => { const rows = ['valid','expired','future','exhausted','inactive','foreign-currency','missing-currency','zero','invalid','priority','percentage'].map(slug => tour(slug, { pricingOptions: [{ price: 80 }] })); await Attraction.collection.insertMany(rows); const overrides: object[] = [{ discountType: 'fixed', currency: 'EUR', discountValue: 15 }, { validUntil: new Date(0) }, { validFrom: new Date(Date.now() + 1000000) }, { usageCount: 100 }, { isActive: false }, { discountType: 'fixed', currency: 'USD' }, { discountType: 'fixed' }, { discountValue: 0 }, { discountValue: -2 }, {}, { discountValue: 25 }]; await SpecialOffer.collection.insertMany(rows.map((row, i) => offer(row._id, overrides[i]))); await SpecialOffer.collection.insertOne(offer(rows[9]._id, { discountType: 'fixed', currency: 'EUR', discountValue: 12 })); const body = (await get('/attractions', { deals: 'true', limit: 100 }).expect(200)).body; expect(body.data.map((row: any) => row.slug).sort()).toEqual(['percentage','priority','valid']); expect(body.data.find((row: any) => row.slug === 'priority').publicDeal.price).toBe(68); expect(body.data.find((row: any) => row.slug === 'percentage').publicDeal.price).toBe(60); for (const row of body.data) { expect(row.priceFrom).toBe(80); expect(row.__dealOffers).toBeUndefined(); expect(row.publicDeal).not.toHaveProperty('usageCount'); } });
it('deal reads exclude lifecycle/foreign/enquiry/invalid or unrelated was prices and zero/no discount', async () => { await Attraction.collection.insertMany([tour('valid'), tour('foreign', { tenantIds: [foreign] }), tour('draft', { status: 'draft' }), tour('archive', { archivedAt: new Date() }), tour('trash', { trashedAt: new Date() }), tour('enquiry', { enquiryOnly: true }), tour('no-currency', { currency: '' }), tour('zero', { priceFrom: 0 }), tour('no-discount', { pricingOptions: [{ price: 80, originalPrice: 80 }] }), tour('wrong-option', { pricingOptions: [{ price: 90, originalPrice: 100 }] })]); const body = (await get('/attractions', { deals: 'true' }).expect(200)).body; expect(body.data.map((row: any) => row.slug)).toEqual(['valid']); });
it('deals validate input, keep source fallback, failure distinct from empty and retry', async () => { await Attraction.collection.insertOne(tour('valid')); for (const query of [{ deals: 'false' }, { deals: 'true', pagination: undefined }, { deals: 'true', scope: 'admin' }, { deals: 'true', 'deals[x]': 'true' }]) await get('/attractions', query).expect(400); await request(app).get('/attractions').query({ deals: 'true', pagination: 'cursor' }).expect(400); const body = (await get('/attractions', { deals: 'true', locale: 'ar', localeFallback: 'source' }).expect(200)).body; expect(body.data[0]).toMatchObject({ resolvedLocale: 'en', publicDeal: { price: 80 } }); const spy = jest.spyOn(Attraction, 'aggregate').mockRejectedValueOnce(Error('Unavailable')); await get('/attractions', { deals: 'true' }).expect(500); spy.mockRestore(); expect((await get('/attractions', { deals: 'true' }).expect(200)).body.pagination.total).toBe(1); });

it('current-source publication boundaries and Royal strict fallback survive both new reads', async () => {
 const date = new Date(); const port = destination('Port', { updatedAt: date }); const ride = tour('Port', { updatedAt: date }); await Destination.collection.insertOne(port); await Attraction.collection.insertOne(ride);
 await DestinationTranslation.collection.insertMany([{ tenantId: owner, destinationId: port._id, locale: 'ar', slug: 'ar-port', status: 'draft', sourceUpdatedAt: date, content: { name: 'Invisible', country: 'Invisible' } }, { tenantId: owner, destinationId: port._id, locale: 'de', slug: 'de-port', status: 'published', sourceUpdatedAt: new Date(0), content: { name: 'Invisible', country: 'Invisible' } }]);
 await AttractionTranslation.collection.insertMany([{ tenantId: owner, attractionId: ride._id, locale: 'ar', slug: 'ar-tour', status: 'draft', sourceUpdatedAt: date, content: { title: 'Invisible' } }, { tenantId: owner, attractionId: ride._id, locale: 'de', slug: 'de-tour', status: 'published', sourceUpdatedAt: new Date(0), content: { title: 'Invisible' } }]);
 for (const locale of ['ar','de']) { for (const [path, params] of [['/destinations', {}], ['/attractions', { deals: 'true' }]] as const) { const body = (await get(path, { ...params, locale, localeFallback: 'source' }).expect(200)).body; expect(body.pagination.total).toBe(1); expect(body.data[0].resolvedLocale).toBe('en'); expect((await get(path, { ...params, locale, localeFallback: 'source', search: 'Invisible' }).expect(200)).body.pagination.total).toBe(0); } }
 await Tenant.collection.updateOne({ _id: owner }, { $set: { slug: 'royal-cruise-hurghada' } });
 expect((await get('/destinations', { locale: 'ar', localeFallback: 'source' }).expect(200)).body.pagination.total).toBe(0);
 expect((await get('/attractions', { deals: 'true', locale: 'ar', localeFallback: 'source' }).expect(200)).body.pagination.total).toBe(0);
});
it('display comparison matches discounted advertised option without mutating its raw money and excludes slot-only mismatches', async () => { await Attraction.collection.insertMany([tour('discounted', { priceFrom: 72, pricingOptions: [{ price: 80, discountPercentage: 10, originalPrice: 100 }] }), tour('different-slot', { priceFrom: 50, pricingOptions: [{ price: 80, originalPrice: 100, timeSlots: [{ adultPrice: 50 }] }] })]); const body = (await get('/attractions', { deals: 'true' }).expect(200)).body; expect(body.pagination.total).toBe(1); expect(body.data[0]).toMatchObject({ slug: 'discounted', priceFrom: 72, pricingOptions: [{ price: 80, discountPercentage: 10 }], publicDeal: { source: 'was-price', price: 72, originalPrice: 100 } }); });
it('offer expiration between cursor reads is freshly enforced with no stale deal and legacy offset shape unchanged', async () => { const rows = Array.from({ length: 9 }, (_, i) => tour(`fresh-${i}`, { priceFrom: 80+i, pricingOptions: [{ price: 80+i }] })); await Attraction.collection.insertMany(rows); await SpecialOffer.collection.insertMany(rows.map(row => offer(row._id))); const first = (await get('/attractions', { deals: 'true', sort: 'price-low' }).expect(200)).body; await SpecialOffer.collection.updateOne({ attractionId: rows[8]._id }, { $set: { validUntil: new Date(0) } }); const last = (await get('/attractions', { deals: 'true', sort: 'price-low', cursor: first.pagination.nextCursor }).expect(200)).body; expect(last.pagination.total).toBe(8); expect(last.data.map((row: any) => row.slug)).toEqual(['fresh-7']); const legacy = (await request(app).get('/attractions').query({ tenantId: String(owner), page: 1, limit: 100 }).expect(200)).body; expect(legacy.pagination.page).toBe(1); expect(legacy.pagination.total).toBe(9); expect(legacy.data.every((row: any) => row.publicDeal === undefined)).toBe(true); await Destination.collection.insertOne(destination('fresh-0')); const destinations = (await request(app).get('/destinations').query({ tenantId: String(owner), page: 1, limit: 20 }).expect(200)).body; expect(destinations.pagination.page).toBe(1); expect(destinations.data[0].name).toBe('fresh-0'); });

it('percentage and option display rounding follow checkout half-up cents rather than Mongo banker rounding', async () => { const ride = tour('fraction', { priceFrom: 1, pricingOptions: [{ price: 1 }] }); await Attraction.collection.insertOne(ride); await SpecialOffer.collection.insertOne(offer(ride._id, { discountValue: 2.5 })); const body = (await get('/attractions', { deals: 'true' }).expect(200)).body; expect(body.data[0].publicDeal.price).toBe(0.97); });

it('never advertises conditional group/resident or slot-only unit discounts', async () => { const rows = [tour('group', { pricingOptions: [{ price: 80, minParticipants: 2, originalPrice: 100 }] }), tour('resident', { priceFrom: 60, pricingOptions: [{ price: 80, residentPrice: 60, originalPrice: 100 }] }), tour('slot', { priceFrom: 60, pricingOptions: [{ price: 80, timeSlots: [{ adultPrice: 60 }] }] })]; await Attraction.collection.insertMany(rows); await SpecialOffer.collection.insertMany(rows.map(row => offer(row._id, { discountType: 'fixed', currency: 'EUR', discountValue: 10 }))); expect((await get('/attractions', { deals: 'true' }).expect(200)).body.pagination.total).toBe(0); });
