import express from 'express';
import request from 'supertest';
import mongoose, { Types } from 'mongoose';
import { spawnSync } from 'child_process';
import { MongoMemoryServer } from 'mongodb-memory-server';
import { User } from '../models/User';
import { Tenant } from '../models/Tenant';
import { BlogPost } from '../models/BlogPost';
import journalRoutes from '../routes/journalAdmin.routes';
import blogRoutes from '../routes/blog.routes';
import { sign } from 'jsonwebtoken';
jest.setTimeout(120000);
const app = express(); app.use(express.json()); app.use('/journal', journalRoutes); app.use('/blog', blogRoutes); app.use((error: any, _req: any, res: any, _next: any) => res.status(error.statusCode || 500).json({ error: error.message }));
const a = new Types.ObjectId(), b = new Types.ObjectId(); let mongo: MongoMemoryServer;
const tokens: Record<string, string> = {};
const input = { title: 'Red Sea journal', slug: 'red-sea-journal', excerpt: 'A useful guide.', content: '<h2>Prepare</h2><p>Read this guide.</p><script>alert(1)</script>', featuredImage: '', featuredImageAlt: '', author: 'Editorial Team', category: 'Travel', tags: ['travel'], metaTitle: 'Sea guide', metaDescription: 'Plan your visit.', featured: false };
const url = (post?: string) => `/journal/${a}${post ? `/${post}` : ''}`;
const auth = (role = 'brand-admin') => ({ Authorization: `Bearer ${tokens[role]}` });
async function create() { return (await request(app).post(url()).set(auth()).send(input).expect(201)).body.data; }
beforeAll(async () => { const located = spawnSync('which', ['mongod'], { encoding: 'utf8' }); const systemBinary = located.status === 0 ? located.stdout.trim() : undefined; const version = systemBinary ? spawnSync(systemBinary, ['--version'], { encoding: 'utf8' }).stdout.match(/db version v([\d.]+)/)?.[1] : undefined; mongo = await MongoMemoryServer.create({ binary: { version: version || '7.0.14', ...(systemBinary ? { systemBinary } : {}) } }); await mongoose.connect(mongo.getUri('journal_admin')); await Promise.all([User.init(), Tenant.init(), BlogPost.init()]);
  await Tenant.collection.insertMany([{ _id: a, slug: 'cruise-a', name: 'Cruise A', domain: 'cruise-a.invalid', status: 'active' }, { _id: b, slug: 'cruise-b', name: 'Cruise B', domain: 'cruise-b.invalid', status: 'active' }]);
  for (const role of ['super-admin', 'brand-admin', 'manager', 'editor', 'viewer', 'customer', 'outsider']) { const _id = new Types.ObjectId(); await User.collection.insertOne({ _id, role: role === 'outsider' ? 'brand-admin' : role, email: `${role}@qa.invalid`, status: 'active', assignedTenants: role === 'outsider' ? [b] : [a], tokenVersion: 0 }); tokens[role] = sign({ userId: String(_id), sessionVersion: 0 }, process.env.JWT_SECRET!); }
});
afterAll(async () => { await mongoose.disconnect(); await mongo?.stop(); }); beforeEach(async () => { await BlogPost.deleteMany({}); });
it('requires a valid session, assigned tenant, allowed role, and matching context', async () => { await request(app).get(url()).expect(401); for (const role of ['viewer', 'customer', 'outsider']) await request(app).post(url()).set(auth(role)).send(input).expect(403); await request(app).post(url()).set(auth()).send({ ...input, tenantId: String(b) }).expect(400); await request(app).get(`${url()}?tenantId=${b}`).set(auth()).expect(400); await request(app).get('/journal/bad-id').set(auth()).expect(400); await request(app).get(`/journal/${new Types.ObjectId()}`).set(auth('super-admin')).expect(404); });
it('creates a sanitized draft, never publicly visible until explicit publication', async () => { const post = await create(); expect(post.content).toBe('<h2>Prepare</h2><p>Read this guide.</p>'); expect(post.tenantId).toBe('cruise-a'); expect(post.tenantRef).toBe(String(a)); expect(post.status).toBe('draft'); await request(app).get('/blog/red-sea-journal?tenant=cruise-a').expect(404); expect((await request(app).get('/blog?tenant=cruise-a').expect(200)).body.data).toEqual([]); });
it('supports title-only drafts and rejects unknown fields, unsafe URLs, and empty publication', async () => { const post = (await request(app).post(url()).set(auth()).send({ title: 'Draft', slug: 'draft' }).expect(201)).body.data; await request(app).post(`${url(post._id)}/transition`).set(auth()).send({ action: 'publish', expectedUpdatedAt: post.updatedAt }).expect(400); await request(app).post(url()).set(auth()).send({ ...input, status: 'published' }).expect(400); await request(app).post(url()).set(auth()).send({ ...input, featuredImage: 'javascript:bad()' }).expect(400); });
it('supports publish, unpublish, archive and restore without reopening public access accidentally', async () => { let post = await create(); const original = post.updatedAt; post = (await request(app).post(`${url(post._id)}/transition`).set(auth()).send({ action: 'publish', expectedUpdatedAt: post.updatedAt, publishedAt: '2025-01-01T00:00:00.000Z' }).expect(200)).body.data; expect(post.publishedAt).toBe('2025-01-01T00:00:00.000Z'); await request(app).get('/blog/red-sea-journal?tenant=cruise-a').expect(200); await request(app).put(url(post._id)).set(auth()).send({ ...input, expectedUpdatedAt: post.updatedAt }).expect(409); await request(app).post(`${url(post._id)}/transition`).set(auth()).send({ action: 'archive', expectedUpdatedAt: original }).expect(409); for (const action of ['unpublish', 'archive', 'restore']) { post = (await request(app).post(`${url(post._id)}/transition`).set(auth()).send({ action, expectedUpdatedAt: post.updatedAt }).expect(200)).body.data; await request(app).get('/blog/red-sea-journal?tenant=cruise-a').expect(404); } expect(post.status).toBe('draft'); });
it('fences concurrent writes and preserves the successful update', async () => { const post = await create(); const results = await Promise.all(['One', 'Two'].map(title => request(app).put(url(post._id)).set(auth()).send({ ...input, title, expectedUpdatedAt: post.updatedAt }))); expect(results.map(r => r.status).sort()).toEqual([200,409]); const winner = results.find(r => r.status === 200)!.body.data; expect((await request(app).get(url(post._id)).set(auth()).expect(200)).body.data.title).toBe(winner.title); });
it('fences parallel publication and rejects future publication date or missing cover alt', async () => { const post = await create(); await request(app).post(`${url(post._id)}/transition`).set(auth()).send({ action: 'publish', expectedUpdatedAt: post.updatedAt, publishedAt: '2099-01-01T00:00:00.000Z' }).expect(400); const results = await Promise.all([1,2].map(() => request(app).post(`${url(post._id)}/transition`).set(auth()).send({ action: 'publish', expectedUpdatedAt: post.updatedAt }))); expect(results.map(r => r.status).sort()).toEqual([200,409]); });
it('prevents editors publishing and cross-tenant object access or joins', async () => { const post = await create(); await request(app).post(`${url(post._id)}/transition`).set(auth('editor')).send({ action: 'publish', expectedUpdatedAt: post.updatedAt }).expect(403); await request(app).get(`/journal/${b}/${post._id}`).set(auth('super-admin')).expect(404); await request(app).put(`/journal/${b}/${post._id}`).set(auth('super-admin')).send({ ...input, expectedUpdatedAt: post.updatedAt }).expect(409); await BlogPost.collection.insertOne({ tenantId: 'cruise-a', tenantRef: b, title: 'Wrong owner', slug: 'wrong-owner', content: 'x', status: 'published' }); await request(app).get('/blog/wrong-owner?tenant=cruise-a').expect(404); });
it('enforces URL uniqueness within each tenant and keeps another tenant independent', async () => { await create(); await request(app).post(url()).set(auth()).send(input).expect(409); await request(app).post(`/journal/${b}`).set(auth('super-admin')).send(input).expect(201); });
it('reaches the list tail through cursor pagination and rejects replay in another filter/site', async () => { for (let i=0;i<7;i++) await BlogPost.create({ ...input, slug: `article-${i}`, title: `Article ${i}`, tenantId: 'cruise-a', tenantRef: a, status: 'draft' }); let cursor: string | undefined; const seen: string[] = []; let firstCursor = ''; do { const response = await request(app).get(url()).set(auth()).query({ limit: 2, ...(cursor ? { cursor } : {}) }).expect(200); seen.push(...response.body.data.posts.map((p: any) => p._id)); cursor = response.body.data.pagination.nextCursor; if (!firstCursor && cursor) firstCursor = cursor; } while(cursor); expect(new Set(seen).size).toBe(7); await request(app).get(url()).set(auth()).query({ cursor: firstCursor, status: 'published' }).expect(400); await request(app).get(`/journal/${b}`).set(auth('super-admin')).query({ cursor: firstCursor }).expect(400); });

it('requires a cover description and rejects attempts to publish an archived article', async () => { let post = (await request(app).post(url()).set(auth()).send({ ...input, featuredImage: 'https://images.invalid/cover.jpg' }).expect(201)).body.data; await request(app).post(`${url(post._id)}/transition`).set(auth()).send({ action: 'publish', expectedUpdatedAt: post.updatedAt }).expect(400); post = (await request(app).post(`${url(post._id)}/transition`).set(auth()).send({ action: 'archive', expectedUpdatedAt: post.updatedAt }).expect(200)).body.data; await request(app).post(`${url(post._id)}/transition`).set(auth()).send({ action: 'publish', expectedUpdatedAt: post.updatedAt }).expect(409); });
it('rejects revoked sessions before any article reads', async () => { const bad = sign({ userId: String((await User.findOne({ role: 'editor' }))!._id), sessionVersion: 99 }, process.env.JWT_SECRET!); await request(app).get(url()).set('Authorization', `Bearer ${bad}`).expect(401); });
