import { Types } from 'mongoose';
import { TenantPresentationTranslation } from '../models/TenantPresentationTranslation';
import { PRESENTATION_LOCALES, presentationSourceTemplate, presentationSourceSnapshot, cleanPresentationContent, localizedTenantPresentation, currentPresentationRows, ownedPresentationSource, PresentationRow } from '../services/tenantPresentationLocalization.service';
const owner=new Types.ObjectId(),pageId=new Types.ObjectId(),foreign=new Types.ObjectId();
const page={_id:pageId,tenantId:owner,slug:'guide',title:'Guide',body:'<p>Meet here <a href="/safaris/quad" title="Read">Read</a><img src="https://img.test/a.jpg" alt="Sea"></p>',metaTitle:'Guide',metaDescription:'Plan your visit',heroDescription:'Visit guide',heroImageAlt:'Beach',heroImage:'https://img.test/hero.jpg',isPublished:true,status:'active',revision:2,sections:[{id:'a',type:'content',title:'Details',body:'<p>More <a href="https://example.test/map">Map</a></p>'},{id:'b',type:'tours',title:'Trips',layout:'horizontal',attractionIds:[String(foreign)]}]};
const tenant={_id:owner,slug:'site-a',name:'Operator',tagline:'Our trips',description:'Explore the sea',heroImages:['https://img.test/a.jpg'],seoSettings:{metaTitle:'Title',metaDescription:'Description',keywords:['sea'],ogImage:'https://img.test/og.jpg'},pageSeo:{version:1,pages:{home:{title:'Home',description:'Our home',heading:'Welcome',ogImage:'https://img.test/home.jpg'}}},navigation:[{label:'Trips',href:'/safaris',columns:[{label:'Region',links:[{label:'Beach',href:'/guide'}]}]}],customPages:[page],defaultCurrency:'EUR',paymentSettings:{secret:'unchanged'},pricingSettings:{fee:5},contactInfo:{email:'operator@example.test'}};
function translated(kind:'tenant'|'page',source:any) {const result=presentationSourceTemplate(kind,source);if(kind==='tenant'){result.tagline='Translated trips';result.description='Translated sea';result.navigation[0].label='Translated menu';result.pageSeo[0].heading='Translated welcome';}else{result.title='Translated guide';result.body=result.body.replace('Meet here','Translated meeting');result.sections[0].body=result.sections[0].body.replace('More','Translated more');}return result;}
const row=(kind:'tenant'|'page',source:any,locale='ar'):PresentationRow=>({tenantId:owner,kind,sourceId:source._id,locale,status:'published',sourceSnapshot:presentationSourceSnapshot(kind,source),content:translated(kind,source)});
it('model has immutable scope and unique compound identity',()=>{for(const key of ['tenantId','kind','sourceId','locale'])expect(TenantPresentationTranslation.schema.path(key).options.immutable).toBe(true);expect(TenantPresentationTranslation.schema.indexes()).toContainEqual([{tenantId:1,kind:1,sourceId:1,locale:1},{unique:true,background:true}]);});
it.each(PRESENTATION_LOCALES)('overlays only existing public tenant prose for %s',locale=>{const result=localizedTenantPresentation(tenant,tenant,owner,locale,[row('tenant',tenant,locale)]);expect(result.resolvedLocale).toBe(locale);expect(result.tagline).toBe('Translated trips');expect(result.name).toBe(tenant.name);for(const key of ['paymentSettings','pricingSettings','defaultCurrency','customPages','contactInfo','heroImages'])expect(result[key]).toEqual((tenant as any)[key]);expect(result.navigation[0].href).toBe('/safaris');expect(result.navigation[0].columns[0].links[0].href).toBe('/guide');expect(result.pageSeo.pages.home.ogImage).toBe(tenant.pageSeo.pages.home.ogImage);expect(result.pageSeo.pages.home).not.toHaveProperty('key');});
it.each(PRESENTATION_LOCALES)('page %s preserves identity, source hierarchy, collections and images',locale=>{const result=localizedTenantPresentation(page,page,owner,locale,[row('page',page,locale)],'page');expect(result.title).toBe('Translated guide');for(const key of ['_id','slug','revision','heroImage','status'])expect(result[key]).toEqual((page as any)[key]);expect(result.sections[1]).toEqual(page.sections[1]);expect(result.body).toContain('href="/safaris/quad"');expect(result.body).toContain('src="https://img.test/a.jpg"');});
it.each(['draft','archived'])('unpublished translation %s falls back truthfully',status=>{const r=row('tenant',tenant);r.status=status;expect(localizedTenantPresentation(tenant,tenant,owner,'ar',[r])).toMatchObject({tagline:tenant.tagline,resolvedLocale:'en',translationStatus:'missing',publishedPresentationLocales:[]});});
it.each([{tenantId:foreign},{sourceId:foreign},{kind:'page' as const},{locale:'es'},{content:{...translated('tenant',tenant),defaultCurrency:'USD'}}])('rejects foreign or hostile translation %j',change=>{const r={...row('tenant',tenant),...change};expect(currentPresentationRows(owner,'tenant',tenant,[r])).toEqual([]);});
it('rejects ambiguous duplicate publication for a locale',()=>expect(currentPresentationRows(owner,'tenant',tenant,[row('tenant',tenant),row('tenant',tenant)])).toEqual([]));
it('source English remains unchanged with published translations',()=>expect(localizedTenantPresentation(tenant,tenant,owner,'en',[row('tenant',tenant)])).toMatchObject({tagline:tenant.tagline,resolvedLocale:'en',translationStatus:'source'}));
it('operational updates do not invalidate presentation while authored edits do',()=>{const r=row('tenant',tenant);expect(currentPresentationRows(owner,'tenant',{...tenant,updatedAt:new Date(),defaultCurrency:'USD',pricingSettings:{fee:10}},[r])).toHaveLength(1);expect(currentPresentationRows(owner,'tenant',{...tenant,description:'Edited description'},[r])).toEqual([]);expect(currentPresentationRows(owner,'tenant',{...tenant,navigation:[{label:'Trips',href:'/other'}]},[r])).toEqual([]);});
it.each([{isPublished:false},{status:'archived'},{trashedAt:new Date()}])('does not overlay retired page %j',change=>expect(currentPresentationRows(owner,'page',{...page,...change},[row('page',page)])).toEqual([]));
it('requires verified containing tenant ownership for embedded pages',()=>{expect(ownedPresentationSource(tenant,'page',pageId).tenantId).toEqual(owner);expect(()=>ownedPresentationSource(tenant,'page',foreign)).toThrow('Foreign source');expect(()=>ownedPresentationSource(tenant,'tenant',foreign)).toThrow('Foreign source');expect(currentPresentationRows(owner,'page',{...page,tenantId:foreign},[row('page',page)])).toEqual([]);});
it.each(['title','body','metaTitle','heroDescription'])('requires existing %s information',key=>{const content=translated('page',page);content[key]='';expect(()=>cleanPresentationContent('page',page,content)).toThrow();});
it('forbids invented information in absent fields',()=>{const source={...page,heroDescription:''};const content=presentationSourceTemplate('page',source);content.heroDescription='Invented benefit';expect(()=>cleanPresentationContent('page',source,content)).toThrow('Do not invent');});
it.each(['missing','duplicate','foreign','reorder'])('preserves complete section identity %s',mode=>{const content=translated('page',page);if(mode==='missing')content.sections.pop();else if(mode==='duplicate')content.sections[1].id='a';else if(mode==='foreign')content.sections[1].id='other';else content.sections.reverse();expect(()=>cleanPresentationContent('page',page,content)).toThrow();});
it('preserves every navigation label and existing source SEO key',()=>{const content=translated('tenant',tenant);content.navigation[0].columns[0].links=[];expect(()=>cleanPresentationContent('tenant',tenant,content)).toThrow('Translate every');const seo=translated('tenant',tenant);seo.pageSeo[0].key='about';expect(()=>cleanPresentationContent('tenant',tenant,seo)).toThrow('Preserve');});
it.each(['href="/other"','href="https://foreign.test/"','href="javascript:alert(1)"'])('prevents changed authored link %s',replacement=>{const content=translated('page',page);content.body=content.body.replace('href="/safaris/quad"',replacement);expect(()=>cleanPresentationContent('page',page,content)).toThrow('Preserve every');});
it('prevents changed image collection',()=>{const content=translated('page',page);content.body=content.body.replace('https://img.test/a.jpg','https://img.test/b.jpg');expect(()=>cleanPresentationContent('page',page,content)).toThrow('Preserve every');});
it('sanitizes script and handlers before publication without changing resources',()=>{const content=translated('page',page);content.body+='<script>alert(1)</script><p onclick="attack()">Safe</p>';const clean=cleanPresentationContent('page',page,content);expect(clean.body).not.toMatch(/script|onclick/);expect(clean.body).toContain('Safe');});
it('does not mutate input source or translation while sanitizing/overlaying',()=>{const r=row('page',page);const before=JSON.stringify({page,r});localizedTenantPresentation(page,page,owner,'ar',[r],'page');expect(JSON.stringify({page,r})).toBe(before);});

import { exportTenantPresentationSource, presentationDigest, tenantPresentationPayload } from '../services/tenantPresentationMigration.service';
it('export contains every published source but excludes drafts/archives/operational fields',()=>{const source={...tenant,status:'active',customDomain:'site.invalid',customPages:[page,{...page,_id:new Types.ObjectId(),isPublished:false},{...page,_id:new Types.ObjectId(),status:'archived'}]};const exported=exportTenantPresentationSource(source);expect(exported.sources.map(item=>item.sourceId)).toEqual([String(owner),String(pageId)]);expect(JSON.stringify(exported)).not.toMatch(/paymentSettings|secret|pricingSettings|defaultCurrency|contactInfo/);expect(presentationDigest(exported)).toBe(presentationDigest(exportTenantPresentationSource({...source,updatedAt:new Date(),pricingSettings:{fee:99}})));});
it('requires explicit complete four-language migration intent and rejects settings payload',()=>{const payload={tenantId:String(owner),tenantSlug:'site-a',domain:'site.invalid',sourceSha256:'a'.repeat(64),locales:['ar','de','ru','fr'],rows:PRESENTATION_LOCALES.map(locale=>({kind:'tenant',sourceId:String(owner),locale,content:translated('tenant',tenant)}))};expect(tenantPresentationPayload.safeParse(payload).success).toBe(true);for(const locales of [['ar'],['ar','de','ru','ru'],['ar','de','ru','es']])expect(tenantPresentationPayload.safeParse({...payload,locales}).success).toBe(false);expect(tenantPresentationPayload.safeParse({...payload,paymentSettings:{enabled:true}}).success).toBe(false);});

it.each([{_id:foreign},{id:foreign},{slug:'foreign-site'}])('never overlays another public DTO identity %j',change=>{const result=localizedTenantPresentation({...tenant,...change},tenant,owner,'ar',[row('tenant',tenant)]);expect(result.resolvedLocale).toBe('en');expect(result.publishedPresentationLocales).toEqual([]);expect(result.tagline).toBe(tenant.tagline);});
import {localizedPublicSitePresentation} from '../services/tenantPresentationLocalization.service';
it('site wrapper localizes each published page independently and never advertises incomplete site-wide content',()=>{const complete=[...PRESENTATION_LOCALES.map(locale=>row('tenant',tenant,locale)),...PRESENTATION_LOCALES.map(locale=>row('page',page,locale))];const result=localizedPublicSitePresentation(tenant,tenant,'ar',complete);expect(result.customPages[0]).toMatchObject({title:'Translated guide',resolvedLocale:'ar'});expect(result.publishedSiteLocales).toEqual(PRESENTATION_LOCALES);const missing=localizedPublicSitePresentation(tenant,tenant,'ar',complete.filter(r=>!(r.kind==='page'&&r.locale==='ar')));expect(missing.customPages[0]).toMatchObject({title:page.title,resolvedLocale:'en',translationStatus:'missing'});expect(missing.publishedSiteLocales).toEqual(['de','ru','fr']);});

it('site wrapper never advertises another DTO as owner-qualified publication',()=>{const result=localizedPublicSitePresentation({...tenant,_id:foreign},tenant,'ar',[row('tenant',tenant),row('page',page)]);expect(result.publishedSiteLocales).toEqual([]);expect(result.publishedPresentationLocales).toEqual([]);expect(result.customPages[0].title).toBe(page.title);});
import {presentationReadScope} from '../services/tenantPresentationLocalization.service';
it('public DB scope reads only this owner and its current published entities, excluding history',()=>{const scope=presentationReadScope({...tenant,customPages:[page,{...page,_id:foreign,status:'archived'}]});expect(scope).toEqual({tenantId:owner,status:'published',locale:{$in:[...PRESENTATION_LOCALES]},$or:[{kind:'tenant',sourceId:owner},{kind:'page',sourceId:{$in:[pageId]}}]});expect(()=>presentationReadScope({...tenant,_id:'invalid'})).toThrow('identity');});

it('source export never includes legacy private extras or script content outside public prose',()=>{const source={...tenant,status:'active',customDomain:'site.invalid',navigation:[{...tenant.navigation[0],privateValue:'hidden-marker'}],customPages:[{...page,body:page.body+'<script>hidden-marker</script>',sections:page.sections.map(section=>({...section,privateValue:'hidden-marker'}))}]};expect(JSON.stringify(exportTenantPresentationSource(source))).not.toContain('hidden-marker');});
