import { Response, NextFunction } from 'express';
import { Types } from 'mongoose';
import { z } from 'zod';
import { Destination } from '../models/Destination';
import { DestinationTranslation } from '../models/DestinationTranslation';
import { Tenant } from '../models/Tenant';
import { Attraction } from '../models/Attraction';
import { AuthRequest } from '../types';
import { tenantPickupDestinationSlugs } from '../utils/pickupDestinations';
import { TranslationError } from '../services/attractionLocalization.service';
import { destinationTranslationContent, cleanDestinationTranslation, validateDestinationTranslation } from '../services/destinationLocalization.service';
const input = z.object({ slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(180), sourceUpdatedAt: z.string().datetime(), expectedUpdatedAt: z.string().datetime().optional(), content: destinationTranslationContent }).strict();
async function scope(req: AuthRequest) { const parsed = z.object({ tenantId: z.string().regex(/^[a-f\d]{24}$/i), destinationId: z.string().regex(/^[a-f\d]{24}$/i), locale: z.enum(['de','ru']) }).safeParse(req.params); if (!parsed.success) throw new TranslationError('Invalid destination translation address'); const { tenantId,destinationId,locale } = parsed.data; if (!req.user || (req.user.role !== 'super-admin' && !req.user.assignedTenants.some(id => String(id) === tenantId))) throw new TranslationError('Access denied to this site',403); if ((req.query.tenantId && req.query.tenantId !== tenantId) || req.body?.tenantId || req.body?.destinationId || req.body?.locale) throw new TranslationError('Conflicting destination context'); const tenant = await Tenant.findById(tenantId).lean(); const source = await Destination.findOne({ _id: destinationId,isActive: true }).lean(); if (!tenant || !source || !source.updatedAt) throw new TranslationError('Destination not found',404); if (!tenantPickupDestinationSlugs(tenant as never).includes(source.slug) && !await Attraction.exists({ tenantIds: tenant._id,status: 'active','destination.city': source.name, archivedAt: { $exists: false },trashedAt: { $exists: false } })) throw new TranslationError('Destination not available for this site',404); return { source,filter: { tenantId: new Types.ObjectId(tenantId),destinationId: new Types.ObjectId(destinationId),locale } }; }
const failure = (error: any,next: NextFunction) => next(error?.code === 11000 ? new TranslationError('This translation or URL exists. Reload before saving.',409) : error);
export async function getDestinationTranslation(req: AuthRequest,res: Response,next: NextFunction) { try { const { source,filter } = await scope(req); const translation = await DestinationTranslation.findOne(filter).lean(); res.setHeader('Cache-Control','private, no-store'); res.json({ success: true,data: { source: { id: String(source._id),slug: source.slug,updatedAt: source.updatedAt,content: destinationTranslationContent.parse({ name: source.name,country: source.country,description: source.description,shortDescription: source.shortDescription,highlights: source.highlights || [],bestTimeToVisit: source.bestTimeToVisit || '',tags: source.tags || [] }) },translation,stale: !!translation && +translation.sourceUpdatedAt !== +source.updatedAt } }); } catch(error) { failure(error,next); } }
export async function saveDestinationTranslation(req: AuthRequest,res: Response,next: NextFunction) { try { const { source,filter } = await scope(req); const parsed = input.safeParse(req.body); if (!parsed.success) throw new TranslationError('Invalid destination translation content'); const { slug,sourceUpdatedAt,expectedUpdatedAt } = parsed.data; if (source.updatedAt.toISOString() !== sourceUpdatedAt) throw new TranslationError('The source destination changed. Reload before translating.',409); const content = cleanDestinationTranslation(parsed.data.content); validateDestinationTranslation(source,content); if (await Destination.exists({ _id: { $ne: source._id },slug }) || await DestinationTranslation.exists({ tenantId: filter.tenantId,destinationId: { $ne: source._id },slug })) throw new TranslationError('Another destination uses this URL.',409); const translation = expectedUpdatedAt ? await DestinationTranslation.findOneAndUpdate({ ...filter,status: 'draft',updatedAt: new Date(expectedUpdatedAt) },{ $set: { slug,content,sourceUpdatedAt: new Date(sourceUpdatedAt),updatedAt: new Date(Math.max(Date.now(),Date.parse(expectedUpdatedAt)+1)) } },{ new: true,timestamps: false,runValidators: true }).lean() : (await DestinationTranslation.create({ ...filter,slug,content,sourceUpdatedAt: new Date(sourceUpdatedAt),status: 'draft' })).toObject(); if (!translation) throw new TranslationError('The translation changed or is published. Reload and unpublish before editing.',409); res.status(expectedUpdatedAt ? 200 : 201).json({ success: true,data: translation }); } catch(error) { failure(error,next); } }
export async function transitionDestinationTranslation(req: AuthRequest,res: Response,next: NextFunction) { try { const { source,filter } = await scope(req); const parsed = z.object({ expectedUpdatedAt: z.string().datetime(),action: z.enum(['publish','unpublish']) }).strict().safeParse(req.body); if (!parsed.success) throw new TranslationError('Invalid publication request'); const { expectedUpdatedAt,action } = parsed.data; const match = { ...filter,status: action === 'publish' ? 'draft' : 'published',updatedAt: new Date(expectedUpdatedAt) }; const current = await DestinationTranslation.findOne(match).lean(); if (!current) throw new TranslationError('Translation changed. Reload before publishing.',409); if (action === 'publish') { if (+current.sourceUpdatedAt !== +source.updatedAt) throw new TranslationError('The source changed. Refresh this translation first.',409); validateDestinationTranslation(source,destinationTranslationContent.parse(current.content)); if (await Destination.exists({ _id: { $ne: source._id },slug: current.slug }) || await DestinationTranslation.exists({ tenantId: filter.tenantId,destinationId: { $ne: source._id },slug: current.slug })) throw new TranslationError('Another destination uses this URL.',409); } const translation = await DestinationTranslation.findOneAndUpdate(match,{ $set: { status: action === 'publish' ? 'published' : 'draft',updatedAt: new Date(Math.max(Date.now(),Date.parse(expectedUpdatedAt)+1)) } },{ new: true,timestamps: false }).lean(); if (!translation) throw new TranslationError('Translation changed. Reload before publishing.',409); res.json({ success: true,data: translation }); } catch(error) { failure(error,next); } }
